### ISSUE TITLE
Suspend problem

### ISSUE THREAD

**Issue by antonl1911** [raphael/linux-samus#107]
Does anyone expiriences problems with suspend on current version (4.4.1-5)? When I call systemctl suspend, the screen just stops refreshing and I have to press power button for Pixel to shutdown.

**Comment by colemickens** [comment]
I still encounter [this issue](https://github.com/raphael/linux-samus/issues/65) on a daily basis, which sounds similar to your issue. I've had it on every kernel I've ever used on this thing. https://github.com/raphael/linux-samus/issues/65 (TBH, it will probably keep me from buying Pixels in the future.)

**Comment by aa0na** [comment]
i don't have this issue.  i have my power buttom mapped to suspend, not power off as i hit it too often by accident.

**Comment by raphael** [comment]
Same here, I use suspend every day with no issue.
