### ISSUE TITLE
Submodule splitting by distro?

### ISSUE THREAD

**Issue by ehegnes** [raphael/linux-samus#109]
I was going to post this as a comment for #89, but I felt it would get more attention/criticism as its own issue:

> I wonder if it would make sense to delegate submodules to people interested in maintaining this code for less used distros (Fedora, Gentoo, etc.). That way we can include compatibility for more distros without drastically increasing the size of the main project (separate repos for separate configs; selectively doing `git submodule {update,init}` would decrease cloning time for most users).
> 
> Of course, this adds complexity to the project and it requires more active developers to maintain their own repos.
> 
> For example, the main `linux-samus` repo could contain all of the setup scripts and the main configuration files, and there could be submodule directories such as `linux-samus/distros/{ubuntu,arch,gentoo,fedora}` with the modified kernels pre-built...

> ...alternatively, we could make use of GitHub's releases feature to upload pre-built kernel images instead of including them in the main repo to reduce the size of the repo.

Any thoughts on this? Am I turning a tiny issue into a complex problem?

**Comment by raphael** [comment]
I would be happy to add submodules to distro specific repo. My guess though is that it will be difficult to find maintainers. Something that would be more helpful IMO would be for someone to maintain a PPA for this kernel. It would then be possible to remove all the builds from the repo which would make it a lot easier to maintain.

**Comment by ehegnes** [comment]
Ah, I suppose it would make more sense to outsource building to respective package managers, if possible. I would be glad to maintain a Gentoo ebuild on an overlay, but I am not too keen on maintaining a PPA. :/ Perhaps another user would be so gracious?

**Comment by ehegnes** [comment]
@raphael, after some consideration, I would be willing to maintain a PPA in the interest of removing builds from the repo. Shall I go ahead and create a team on Launchpad so that you may have privileges as well?

**Comment by raphael** [comment]
I had started a PPA here: https://launchpad.net/~simon-raphael/+archive/ubuntu/linux-samus 
Was never successful in doing the right sequence of incantation to upload the kernel though. Create your own and feel free to copy whatever you want from it. I would really love it if you could make it work, the current repo weight 1.3 GB - it would be a fraction of that without the embedded builds...

**Comment by ehegnes** [comment]
@raphael, I've created a PPA and meta packages for the PPA that will install all of the required components (deb files) for different versions, but I'm wondering how you did the package building. Having multiple packages for a single kernel is a weird concept for me. How do you generate the various *.deb files?

**Comment by raphael** [comment]
That's just what `make deb-pkg` produces. For the PPA though you need to produce source packages - that's what I haven't been able to do on archlinux as it requires a debian tool chain.
