### ISSUE TITLE
Bad Return Status for Module Build

### ISSUE THREAD

**Issue by Pajellen** [raphael/linux-samus#110]
**Error! Bad return status for module build on kernel: 4.4.1ph+ (x86_64)
Consult /var/lib/dkms/ndiswrapper/1.59/build/make.log for more information.**

I get this error each time I try to install the .deb packages for the kernel, running Linux Mint 17.3; If I try to boot it I get a black screen even If I select Recovery 4.4.1. Booting a generic 4.4.1 kernel works fine albeit without the specific Samus kernel improvements. I have tried rebuilding the git clone twice on two fresh installs and each time I get this same error on the same line during the dpkg install. Any ideas? Here is a full dump of the dpkg install output and I have attached the make.log listed in the error code as well.
[SAMUS KERNEL.txt](https://github.com/raphael/linux-samus/files/131695/SAMUS.KERNEL.txt)

**Selecting previously unselected package linux-firmware-image-4.4.1ph+.
(Reading database ... 197294 files and directories currently installed.)
Preparing to unpack linux-firmware-image-4.4.1ph+_4.4.1ph+-2_amd64.deb ...
Unpacking linux-firmware-image-4.4.1ph+ (4.4.1ph+-2) ...
Selecting previously unselected package linux-headers-4.4.1ph+.
Preparing to unpack linux-headers-4.4.1ph+_4.4.1ph+-2_amd64.deb ...
Unpacking linux-headers-4.4.1ph+ (4.4.1ph+-2) ...
Selecting previously unselected package linux-image-4.4.1ph+.
Preparing to unpack linux-image-4.4.1ph+_4.4.1ph+-2_amd64.deb ...
Unpacking linux-image-4.4.1ph+ (4.4.1ph+-2) ...
Preparing to unpack linux-libc-dev_4.4.1ph+-2_amd64.deb ...
Unpacking linux-libc-dev (4.4.1ph+-2) over (4.4.1ph+-2) ...
Setting up linux-firmware-image-4.4.1ph+ (4.4.1ph+-2) ...
Setting up linux-headers-4.4.1ph+ (4.4.1ph+-2) ...
Setting up linux-image-4.4.1ph+ (4.4.1ph+-2) ...
Error! Bad return status for module build on kernel: 4.4.1ph+ (x86_64)
Consult /var/lib/dkms/ndiswrapper/1.59/build/make.log for more information.
update-initramfs: Generating /boot/initrd.img-4.4.1ph+
W: Possible missing firmware /lib/firmware/i915/bxt_dmc_ver1.bin for module i915
W: Possible missing firmware /lib/firmware/i915/skl_guc_ver4.bin for module i915
Warning: No support for locale: en_US.utf8
Generating grub configuration file ...
Warning: Setting GRUB_TIMEOUT to a non-zero value when GRUB_HIDDEN_TIMEOUT is set is no longer supported.
Found linux image: /boot/vmlinuz-4.4.1-040401-generic
Found initrd image: /boot/initrd.img-4.4.1-040401-generic
Found linux image: /boot/vmlinuz-4.4.1ph+
Found initrd image: /boot/initrd.img-4.4.1ph+
Found linux image: /boot/vmlinuz-3.19.0-32-generic
Found initrd image: /boot/initrd.img-3.19.0-32-generic
Found memtest86+ image: /boot/memtest86+.elf
Found memtest86+ image: /boot/memtest86+.bin
  No volume groups found
done
Setting up linux-libc-dev (4.4.1ph+-2) **...

**Comment by raphael** [comment]
What does the log file contain?

**Comment by Pajellen** [comment]
This is what it contained:

**DKMS make.log for ndiswrapper-1.59 for kernel 4.4.1ph+ (x86_64)
Mon Feb 15 18:30:46 CST 2016
make: Entering directory `/usr/src/linux-headers-4.4.1ph+'
  LD      /var/lib/dkms/ndiswrapper/1.59/build/built-in.o
  MKEXPORT /var/lib/dkms/ndiswrapper/1.59/build/crt_exports.h
  MKEXPORT /var/lib/dkms/ndiswrapper/1.59/build/hal_exports.h
  MKEXPORT /var/lib/dkms/ndiswrapper/1.59/build/ndis_exports.h
  MKEXPORT /var/lib/dkms/ndiswrapper/1.59/build/ntoskernel_exports.h
  MKEXPORT /var/lib/dkms/ndiswrapper/1.59/build/ntoskernel_io_exports.h
  MKEXPORT /var/lib/dkms/ndiswrapper/1.59/build/rtl_exports.h
  MKEXPORT /var/lib/dkms/ndiswrapper/1.59/build/usb_exports.h
  MKSTUBS /var/lib/dkms/ndiswrapper/1.59/build/win2lin_stubs.h
  CC [M]  /var/lib/dkms/ndiswrapper/1.59/build/crt.o
  CC [M]  /var/lib/dkms/ndiswrapper/1.59/build/hal.o
  CC [M]  /var/lib/dkms/ndiswrapper/1.59/build/iw_ndis.o
  CC [M]  /var/lib/dkms/ndiswrapper/1.59/build/loader.o
/var/lib/dkms/ndiswrapper/1.59/build/loader.c: In function ‘load_sys_files’:
/var/lib/dkms/ndiswrapper/1.59/build/loader.c:157:4: error: implicit declaration of function ‘__vmalloc’ [-Werror=implicit-function-declaration]
    __vmalloc(load_driver->sys_files[i].size,
    ^
/var/lib/dkms/ndiswrapper/1.59/build/loader.c:156:19: warning: assignment makes pointer from integer without a cast [enabled by default]
   pe_image->image =
                   ^
/var/lib/dkms/ndiswrapper/1.59/build/loader.c:207:5: error: implicit declaration of function ‘vfree’ [-Werror=implicit-function-declaration]
     vfree(driver->pe_images[i].image);
     ^
/var/lib/dkms/ndiswrapper/1.59/build/loader.c: In function ‘add_bin_file’:
/var/lib/dkms/ndiswrapper/1.59/build/loader.c:298:2: error: implicit declaration of function ‘vmalloc’ [-Werror=implicit-function-declaration]
  bin_file->data = vmalloc(driver_file->size);
  ^
/var/lib/dkms/ndiswrapper/1.59/build/loader.c:298:17: warning: assignment makes pointer from integer without a cast [enabled by default]
  bin_file->data = vmalloc(driver_file->size);
                 ^
/var/lib/dkms/ndiswrapper/1.59/build/loader.c: In function ‘wrapper_ioctl’:
/var/lib/dkms/ndiswrapper/1.59/build/loader.c:789:15: warning: assignment makes pointer from integer without a cast [enabled by default]
   load_driver = vmalloc(sizeof(*load_driver));
               ^
/var/lib/dkms/ndiswrapper/1.59/build/loader.c: In function ‘wrapper_ioctl_compat’:
/var/lib/dkms/ndiswrapper/1.59/build/loader.c:884:11: warning: assignment makes pointer from integer without a cast [enabled by default]
   kdriver = vmalloc(sizeof(*kdriver));
           ^
cc1: some warnings being treated as errors
make[1]: *** [/var/lib/dkms/ndiswrapper/1.59/build/loader.o] Error 1
make: *** [_module_/var/lib/dkms/ndiswrapper/1.59/build] Error 2
make: Leaving directory `/usr/src/linux-headers-4.4.1ph+'
**

I have since moved on to GalliumOS and the build issue didn't show up, must be something with Linux Mint make module that caused the issue. I can move back to it if you want to troubleshoot more.

**Comment by raphael** [comment]
Thanks for the update, definitely looks like an issue with Mint, I guess Ubuntu fixed it: https://bugs.launchpad.net/ubuntu/+source/ndiswrapper/+bug/1514243 (see the last comment in particular). Feel free to close this issue.
