### ISSUE TITLE
Loading initial ramdisk after trying to load kernel

### ISSUE THREAD

**Issue by mrananderson** [raphael/linux-samus#111]
Hi,

I used chrx to install ubuntu 15.10 on my chromebook pixel ls. 
I cloned raphael's repo and followed the steps to install the kernel.
I modified the /etc/default/grub to set output to console so that I could select which kernel to load.
My issue is that I am unable to load linux-samus kernel. It is stuck at loading initial ramdisk.
I am able to go back to the old kernel. However I cant seem to load the modified kernel.
Any guidance would be appreciated.

Thanks,
Amit

**Comment by raphael** [comment]
Hello Amit, this issue is commonly reported - not sure we were able to find the root cause. One thing I would try is making sure you have the latest firmware installed for the graphic card. Also check the obvious places for errors (`dmesg`, `/var/log/*.log`, init logs etc.).
