### ISSUE TITLE
Enabling sound step by step didn't work

### ISSUE THREAD

**Issue by ianwalter** [raphael/linux-samus#112]
Here is the error I get when trying to execute the enable the "HiFi" verb step:

```
ian@page:~/linux-samus/scripts/setup$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: bdwrt5677 [bdw-rt5677], device 0: System Playback (*) []
  Subdevices: 0/1
  Subdevice #0: subdevice #0
card 1: HDMI [HDA Intel HDMI], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: HDMI [HDA Intel HDMI], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: HDMI [HDA Intel HDMI], device 8: HDMI 2 [HDMI 2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
ian@page:~/linux-samus/scripts/setup$ ALSA_CONFIG_UCM=ucm/ alsaucm -c bdw-rt5677 set _verb HiFi
ALSA lib utils.c:67:(uc_mgr_config_load) could not open configuration file ucm//bdw-rt5677/bdw-rt5677.conf
ALSA lib parser.c:1211:(load_master_config) error: could not parse configuration for card bdw-rt5677
ALSA lib main.c:803:(snd_use_case_mgr_open) error: failed to import bdw-rt5677 use case configuration -2
alsaucm: error failed to open sound card bdw-rt5677: No such file or directory
```

I'm on a Chromebook Pixel 2 LS running Ubuntu 15.10. 
Anyone have any ideas? Thanks.

**Comment by christianbundy** [comment]
That looks like the error I was getting in #50, do any of the solutions in that thread work for you?

**Comment by nelsonni** [comment]
The `pacmd set-default-sink <index>` command (shown in #50) will allow you to set the default sink, but to switch the currently running sink you will need to use `pacmd set-sink-port <sink> <port>`. Since you already have the `bdwrt5677` device driver running, it would be one of the following:
```bash
# For speakers:
pacmd set-sink-port alsa_output.platform-bdw-rt5677.analog-stereo analog-output-speaker

# For headphones:
pacmd set-sink-port alsa_output.platform-bdw-rt5677.analog-stereo analog-output-headphones
```

**Comment by ianwalter** [comment]
@christianbundy @nelsonni Thank you, but no. platform-bdw-rt5677.analog-stereo was already selected as default and running set-sink-port didn't help either. I think the troubling difference between my issue and yours is that under bdwrt5677 it says `Subdevices: 0/1` but then again I don't know what that means.

I ran `dmesg | grep bdw` like you did and found two errors repeated over and over again:
```
[ (some number) ] bdw-rt5677 bdw-rt5677: ASoC: can't get playback BE for DSP Buffer
[ (some number) ] bdw-rt5677 bdw-rt5677: ASoC: can't get playback BE for DSP Capture
```

**Comment by nelsonni** [comment]
The `Subdevices: 0/1` part seems suspect. According to the ALSA project documentation:
>We use subdevices mainly for hardware which can mix several streams together. It is impractical to have 32 devices with exactly the same capabilities. The subdevices can be opened without a specific address, so the first free subdevice is opened. Also, we temporarily use subdevices for hardware with a lot of streams (I/O connectors) — for example MIDI. There are several limits given by used minor numbers (8 PCM devices per card, 8 MIDI devices per card etc.).

> Source: http://www.alsa-project.org/main/index.php/Asoundrc#The_naming_of_PCM_devices

I suspect that the bdw-rt5677 driver is not being correctly associated with the hardware aliases. The **JACK** plugin might be helpful in this regard. If it exists, what does your `/home/<username>/.asoundrc` file say?

**Comment by ianwalter** [comment]
Ahhh I was setting `ALSA_CONFIG_UCM` to `ucm/` when I was one directory up in `setup/`. After I cd'd to `sound/` the `alsaucm` command worked and so now does my sound. Thanks for your help.

**Comment by ianwalter** [comment]
Just wanted to also note that I used `sudo alsactl restore --file alsa/headphones.state` to get my headphones working properly although if I switch to the external speakers, the channels are reversed.

**Comment by nelsonni** [comment]
My headphones were reversed as well. This can be fixed in `/etc/pulse/default.pa`. http://superuser.com/questions/59481/how-to-swap-stereo-channels-in-ubuntu

**Comment by ianwalter** [comment]
@nelsonni That looks like it reverses everything, is that correct? Did you do something special to reverse your headphones and not your speakers?
