### ISSUE TITLE
ACPID Overhaul

### ISSUE THREAD

**Issue by ehegnes** [raphael/linux-samus#113]
I have a few issues with the way `acpid` configuration is currently being handled:

- The [`sed` commands in `sound.sh`](https://github.com/raphael/linux-samus/blob/master/scripts/setup/sound/sound.sh#L58-L107) subjectively modify a pretty important file ‒ this file may not be the same on all systems.
  - The `sed` commands run nearly indefinitely with my current default `acpid` script, replacing `/etc/acpi/handler.sh` with garbage until my filesystem is entirely full.
- The catch-all script (`handler.sh` for most) is subjectively named by each distribution. Some systems use `default.sh` as the name of their default `acpid` script. This is not currently taken into account and will make the sound script fail on non-conforming systems.
- `acpid` offers an elegant solution to isolate actions for specific events which we are not using.

We should use this isolation to overhaul the current `sound.sh` script to be more compatible by including proper files in `/etc/acpi/actions/` and `/etc/acpi/events/`. This would avoid messing with users' current configurations, and it would trivialize updates.

I'd be glad to overhaul the script, but I need somebody to post what a proper `/etc/acpi/handler.sh` script should look like.

**Comment by nelsonni** [comment]
Here is my `/etc/acpi/handler.sh`:
```bash
#!/bin/bash`
# Default acpi script that takes an entry for all actions
 
function _SwitchPulsePort () {
    sink="alsa_output.platform-bdw-rt5677.analog-stereo"
    port="analog-output-speaker"
 
    if [ "x$1" == "xplug" ] ; then
        port="analog-output-headphones"
    fi
 
    for user in `ps axc -o user,command | grep pulseaudio | cut -f1 -d' ' | sort | uniq`
    do
        uid=`id -u "${user}"`
        pulsepath="/run/user/${uid}/pulse/"
        su "${user}" -c - "PULSE_RUNTIME_PATH=\"${pulsepath}\" pacmd set-sink-port ${sink} ${port}"
    done
}

case "$1" in
    jack/headphone)
        case "$3" in
           plug)
               logger "headphone plugged"
               # alsaucm -c bdw-rt5677 set _verb HiFi set _disdev Headphone
               # alsactl restore -f /opt/samus/speakers.state
               _SwitchPulsePort "$3"
               ;;
           unplug)
               logger "headphone unplugged"
               # alsaucm -c bdw-rt5677 set _verb HiFi set _enadev Headphone
               # alsactl restore -f /opt/samus/headphones.state
               _SwitchPulsePort "$3"
               ;;
           *)
               logger "ACPI action undefined: $3"
               ;;
        esac
        ;;
    button/power)
        case "$2" in
            PBTN|PWRF)
                logger 'PowerButton pressed'
                ;;
            *)
                logger "ACPI action undefined: $2"
                ;;
        esac
        ;;
    button/sleep)
        case "$2" in
            SLPB|SBTN)
                logger 'SleepButton pressed'
                ;;
            *)
                logger "ACPI action undefined: $2"
                ;;
        esac
        ;;
    ac_adapter)
        case "$2" in
            AC|ACAD|ADP0)
                case "$4" in
                    00000000)
                        logger 'AC unpluged'
                        ;;
                    00000001)
                        logger 'AC pluged'
                        ;;
                esac
                ;;
            *)
                logger "ACPI action undefined: $2"
                ;;
        esac
        ;;
    battery)
        case "$2" in
            BAT0)
                case "$4" in
                    00000000)
                        logger 'Battery online'
                        ;;
                    00000001)
                        logger 'Battery offline'
                        ;;
                esac
                ;;
            CPU0)
                ;;
            *)  logger "ACPI action undefined: $2" ;;
        esac
        ;;
    button/lid)
        case "$3" in
            close)
                logger 'LID closed'
                ;;
            open)
                logger 'LID opened'
                ;;
            *)
                logger "ACPI action undefined: $3"
                ;;
    esac
    ;;
    *)
        logger "ACPI group/action undefined: $1 / $2"
        ;;
esac

# vim:set ts=4 sw=4 ft=sh et:
```

**Comment by ehegnes** [comment]
Thank you, @nelsonni!

**Comment by nelsonni** [comment]
Let me know if you need a guinea pig for Arch. I thought about making the `/etc/acpi/actions/` and `/etc/acpi/events/` split when my sound wasn't working correctly, but didn't get around to it. So I'm on board with making the ACPI configuration adhere to the standard structure.

**Comment by mjrosencrantz** [comment]
Sorry slightly off topic, but I'm using ubuntu 16.04 and I'm one of those people that doesn't have handler.sh.  In fact I don't seem to have any file that maps to that:

> find /etc/acpi/
/etc/acpi/
/etc/acpi/ibm-wireless.sh
/etc/acpi/powerbtn.sh
/etc/acpi/tosh-wireless.sh
/etc/acpi/asus-wireless.sh
/etc/acpi/events
/etc/acpi/events/thinkpad-cmos
/etc/acpi/events/asus-keyboard-backlight-up
/etc/acpi/events/asus-keyboard-backlight-down
/etc/acpi/events/lenovo-undock
/etc/acpi/events/asus-wireless-on
/etc/acpi/events/ibm-wireless
/etc/acpi/events/powerbtn
/etc/acpi/events/asus-wireless-off
/etc/acpi/events/tosh-wireless
/etc/acpi/asus-keyboard-backlight.sh
/etc/acpi/undock.sh

Running the sound setup script obviously failed.  Sound actually works but the headphone jack is completely ignored.  Is there an obvious other place to look for this file?

I'd be happy to test your alternative with Ubuntu if you get it working.

**Comment by ehegnes** [comment]
@mjrosencrantz Congratulations! It looks like your entire `acpid` setup is properly isolated. Normally there would be a file in `/etc/apci/events` ([such as this](https://gist.github.com/ehegnes/c0aa9a710ab7ac7ced4c)) that specifies a default action script, but your current setup is much more elegant.

@nelsonni I'll link to the improved branch today for testing purposes before I submit a PR.

**Comment by ehegnes** [comment]
Please try this out and let me know if it works on your systems. I don't have a `/run/user` or `/var/run` directory for Pulse, and maybe others don't as well, so I found the appropriate path in `/tmp` to set `PULSE_RUNTIME_PATH`. This is the only part of my revision that I'm concerned about with regard to compatibility.

**Comment by nelsonni** [comment]
Both 6e4aaf5 and 19e1d3e work for my system. I can see the `jack/headphone HEADPHONE plug` and `jack/headphone HEADPHONE unplug` events in `acpi_listen`.

Wasn't your proposed idea to migrate each event into their own `/etc/acpi/events/` file? All I see is a `/etc/acpi/actions/samus.sh` and `/etc/acpi/events/samus` files being added.

**Comment by ehegnes** [comment]
`/etc/acpi/events/samus` specifies that all `jack/headphone` events should be handled by `/etc/acpi/actions/samus.sh`. I felt that makes the most sense, as both `plug` and `unplug` events will be handled by the same file, thereby reducing code duplication.

My idea was just to stop modifying `/etc/acpi/handler.sh`, which may not always be present or be edited properly by `sed`. Sorry if I led you to believe that I was doing something differently! Did you have a different idea?

**Comment by nelsonni** [comment]
I thought your idea was to get rid of `/etc/acpi/handler.sh` entirely and move all `acpi` events into their own `/etc/acpi/events` and `/etc/acpi/actions` files. My `/etc/acpi/handler.sh` file contains code for handling `jack/headphone`, `button/power`, `button/sleep`, `ac_adapter`, `battery`, and `button/lid` events.

**Comment by ehegnes** [comment]
I would rather not do that, because I can't guarantee that everybody wants the same things to happen for those events. For example, I use a custom script lock my computer before suspending it, and so a generic suspend command on `button/lid CLOSE` would not suit me, and I would have to go change the config anyway. Further, some people may prefer their power button to behave differently by suspending, locking, or even hibernating their computer.

My interest was in correcting the way we handled jack switching, not choosing new default ACPI actions for everybody.

But hey, feel free to isolate more events if you feel that would be beneficial! Some people may really appreciate that. :)

**Comment by nelsonni** [comment]
@ehegnes How do you currently add that custom script? Do you forgo running the `linux-samus/scripts/setup/sound/sound.sh` file after install and instead run your own? According to all of the documentation about regular ACPI configurations, the actions/events files for each set of functions is the standard model. I wasn't thinking of altering the actions associated with events, just breaking them out into their respective files instead of globed together in a single file.

**Comment by ehegnes** [comment]
I still run the `sound.sh` file, since it doesn't modify my default handler. I just [run a script from `/usr/local/bin` on `button/lid LID close` by adding the specification to `/etc/acpi/default.sh`](https://gist.github.com/ehegnes/88f0d91cd0390c2469b9#file-acpid-default-sh-L31). Most people would use `pm-suspend` or `echo -n mem > /sys/power/state` to suspend. Honestly, it doesn't matter much, because I'd be changing the default anyway. And it matters less because there usually isn't a default set for suspending on lid close.

Anyway. If your overhaul is going to move or change any of the files I've added, let me know. You can feel free to just merge my changes with your overhaul before you PR. Less work for me, and lesser chance of merge conflicts. :P But if you're not going to change anything about my overhaul, I'm going to go ahead and PR it myself.

**Comment by ehegnes** [comment]
After thinking on it a little longer, I feel it would make sense to keep my changes in the `scripts/setup/sound` directory separate from a directory where the rest of the ACPI hooks could be overhauled by you. That way people can opt-in to the overhaul.

**Comment by nelsonni** [comment]
@ehegnes I agree that having choices might be the best route. Perhaps a basic script that simply sets up ALSA, and another that builds out the separate `events`/`actions` files for PulseAudio support might be the easy way to cover most configurations.
