### ISSUE TITLE
Losing Keyboard LED state

### ISSUE THREAD

**Issue by ianwalter** [raphael/linux-samus#116]
If I decrease my keyboard LED to 0 and go to sleep, when I wake up the next morning, it is back to 100.
Is this happening to anyone else?

**Comment by ehegnes** [comment]
I'll test tonight and see if that happens. When you say "go to sleep", do you mean you suspend your box, or do you mean that the state resets after a sufficiently long period of time?

**Comment by ianwalter** [comment]
I meant me actually going to sleep haha. Pretty sure it only happens after being suspended, but it seems like there is some sort of time component because it doesn't happen if I only suspend for ~30 seconds.

**Comment by aeroevan** [comment]
The keyboard backlight driver in the chromeos kernel didn't actually check the previous acpi state and just set the brightness to 100 on load.

The patch that was submitted upstream [0] doesn't set the brightness to 100 by default any more.

[0]: https://lkml.org/lkml/2016/3/8/709
