### ISSUE TITLE
Fan control

### ISSUE THREAD

**Issue by ehegnes** [raphael/linux-samus#117]
Does anybody currently have fan control working? I know that [`ectool`](https://www.chromium.org/chromium-os/ec-development) can do this, but `ectool` stopped working for me a few kernel versions ago. It builds, but the `ioctl` operations sent to `/dev/cros_ec` fail. Sometimes the preset fan controller is not aggressive enough for my needs.

At the risk of seeming frivolously motivated, the lack of `ectool` also disables control over the lightbar. ;)

I'm not necessarily looking for a "fix", but since we don't have an IRC, Gitter, or some other such platform, this seems like the most appropriate (only) way to pose such a query.

**Comment by raphael** [comment]
As far as I know `/dev/cros_ec` is Pixel 2013 only and never worked with Pixel 2015.

**Comment by ethanmad** [comment]
@ehegnes You raise a good issue with there not being some other platform for discussion. I've created `#Pixel2015` on freenode for use if we think IRC is a better medium than @raphael's issue tracker. I'll try to stay active on there if there's interest. Or, of course, we could use a different platform with someone else in charge (but I'd gladly give admin privileges if you share your nicks).

**Comment by ehegnes** [comment]
@ethanmad Thanks! I'll setup a bouncer for myself and join so I can stay in the channel. A mention of this channel in the README would likely be helpful! :)

I'm going to close this issue. @raphael, looking at the EC repo that houses `ectool`, I did find a C header file and references in the Makefile that show `/dev/cros_ec` as the device being used specifically for the `samus` board's communication with the EC, and I know it worked for me in the past. Anyway, maybe I'll reopen this later if I solve it.

**Comment by ethanmad** [comment]
I'll submit a PR with the channel name. I noticed something else that could using a fix in the README.
Also, I should be able to provide a few accounts on my ZNC server (znc.ethanmad.com) if anyone needs a bouncer.

**Comment by ehegnes** [comment]
User error! All I had to do was run `ectool` with the `--interface=lpc` flag set.
