### ISSUE TITLE
EC devices get IDs 1 and 2 instead of 0 and 1, blocking lightbar attributes from appearing under /sys

### ISSUE THREAD

**Issue by sprc** [raphael/linux-samus#119]
I did some debugging to try and figure out why the lightbar device attributes weren't available anywhere in /sys. I eventually pinned it down to these two lines inside cros_ec_lightbar_attrs_are_visible in cros_ec_lightbar.c:

Mainline:
```
    if (pdev->id != 0)
        return 0;
```

ChromiumOS tree:
```
    /* TODO(gwendal): Workaround for crbug/412434 */
    if (pdev->id != 0)
        return 0;
```

Basically, if the ID assigned to this EC device is not 0, don't treat it as having a lightbar.

This seems to work fine in ChromeOS because the IDs assigned to the two EC devices it creates are apparently always 0 and 1. However, in Ubuntu, for reasons I'm not totally clear on, those devices are usually getting IDs 1 and 2 instead of 0 and 1.

Ubuntu:
```
$ find /sys/devices 2>/dev/null -name cros-ec*
/sys/devices/platform/cros_ec_lpc.0/cros-ec-ctl.1.auto
/sys/devices/platform/cros_ec_lpc.0/cros-ec-ctl.2.auto
```

ChromeOS:
```
$ find /sys/devices 2>/dev/null -name cros-ec*
/sys/devices/platform/cros_ec_lpc.0/cros-ec-dev.0
/sys/devices/platform/cros_ec_lpc.0/cros-ec-dev.1
/sys/devices/platform/cros_ec_lpc.0/cros-ec-accel.0
```

If I change the line in cros_ec_lightbar.c to check for ID 1 instead of 0, the attributes show up under the first device and echoing commands at them works as expected.

To make things confusing, though, I did notice, _in a single instance_, that I did get 0 and 1 in Ubuntu and the lightbar worked out of the box. It looks like these IDs are handed out sequentially and can apparently vary from one boot to the next, so I don't think we can trust them as a sufficient method for identifying whether this is the EC with a lightbar or not.

We could just comment out these two lines, which would make the attributes show up under both (and they'd only function under the first one).

Alternatively, we could try and find a better way of identifying which one actually has control over the lightbar. I'm not sure what that would involve though. (ID assignment happens in /drivers/mfd/cros_ec.c.)

**Comment by sprc** [comment]
String comparing the ec_name of the device against CROS_EC_DEV_NAME appears to do the trick if no one has anything more graceful.

```
diff --git a/build/linux/drivers/platform/chrome/cros_ec_lightbar.c b/build/linux/drivers/platform/chrome/cros_ec_lightbar.c
index ff76405..b6356b3 100644
--- a/build/linux/drivers/platform/chrome/cros_ec_lightbar.c
+++ b/build/linux/drivers/platform/chrome/cros_ec_lightbar.c
@@ -414,7 +414,12 @@ static umode_t cros_ec_lightbar_attrs_are_visible(struct kobject *kobj,
                                              struct cros_ec_dev, class_dev);
        struct platform_device *pdev = container_of(ec->dev,
                                                   struct platform_device, dev);
-       if (pdev->id != 0)
+       struct cros_ec_platform *pdata = pdev->dev.platform_data;
+       int is_cros_ec;
+
+       is_cros_ec = strcmp(pdata->ec_name, CROS_EC_DEV_NAME);
+
+       if (is_cros_ec != 0)
                return 0;
 
        /* Only instantiate this stuff if the EC has a lightbar */
```

**Comment by raphael** [comment]
Nice! Is that something you could create a patch for in the `scripts` directory? The next step would be to update [apply_patch.sh](https://github.com/raphael/linux-samus/blob/master/scripts/apply_patch.sh) to also apply this new patch. Thank you!
