### ISSUE TITLE
Black Screen on boot

### ISSUE THREAD

**Issue by zedinosaur** [raphael/linux-samus#125]
Picking up from #70 I'm seeing a black screen when booting up as well. I'm able to blind type my disk encryption password and then X boots up just fine. I also had set GRUB_GFXMODE=1280x850 in my /etc/default/grub to not get completely corrupted graphics when grub runs, so that is perhaps interfering?

**Comment by raphael** [comment]
Not sure if that's the issue but I have my GRUB_GFXMODE set at `1280x850x16` (specifying the color depth as well).

**Comment by funkaster** [comment]
OMG!!! I thought I was lost with corrupted boot screen forever. It turns out specifying the depth fixes it. Thanks!!
