### ISSUE TITLE
Is it possible to include trackpad driver from GalliumOS ?

### ISSUE THREAD

**Issue by jonkirkman** [raphael/linux-samus#128]
I've noticed that the trackpad driver used in https://galliumos.org/ behaves almost exactly like ChromeOS. What's the possibility to integrate that driver into this project?

Thank you for all the great work!

**Comment by ehegnes** [comment]
As far as I know, GalliumOS uses the same [driver we use](https://github.com/hugegreenbug/xf86-input-cmt) — it's actually a driver created by the person who started GalliumOS. The only feature I miss from ChromeOS regarding the touchpad is the three-finger swipe to change tabs in Chrome. Can you elaborate on the features that you consider to be missing?

**Comment by jonkirkman** [comment]
That's great to know that it's the same driver. That suggests my configuration just needs to be tweaked. 

The few issues I've experienced are:
- tap to click is less reliable and requires more pressure to register
- two-finger tapping is not enabled
- cursor jumping while typing is much more frequent (trackpad detecting palms)

**Comment by ehegnes** [comment]
I think the Xorg config files are the same as used in GalliumOS, since they're provided by the `xf86-input-cmt` project, but I'll check. I also haven't found palm detection to be as reliable as I would like.

Two-finger tapping works for me. @jonkirkman, are you using X11?

**Comment by jonkirkman** [comment]
Further digging revealed that `xf86-input-cmt` didn't install correctly. Thanks for the tips!

**Comment by raphael** [comment]
so this issue can be closed?
