### ISSUE TITLE
Can't get sound to work and kernel to load

### ISSUE THREAD

**Issue by SimionKreimer** [raphael/linux-samus#130]
Hi all,
I'm probably missing something obvious but could really use the help. I reinstalled Archlinux (Antergos) after briefly switching to ChromeOS to update the SDD firmware (2.3 now, WOOT). The first thing I did was to install linux-samus4 through yaourt. I've reset the system several times and even ran the  grub-mkconfig -o /boot/grub/grub.cfg command, but whenever i run uname -r it returns 4.4.5-1-ARCH. Probably related to this, I can't get the sound to work. I made the .conf file and copied all of the firmware files as the step-by-step instructions directed, but the brw device doesn't show up when I run aplay -l. I think I ran into a similar situation before, but can't recall how I got out. Please, help.

Best, Simion

**Comment by raphael** [comment]
Definitely looks like the kernel wasn't installed properly or maybe it was but it's not the one used to boot the machine. You should see `linux-samus4` in grub and select that - do you see multiple entries in grub?

**Comment by SimionKreimer** [comment]
It seems like it was installed properly, I can see the image in the boot partition, and there were no errors during installation. When I boot up the computer, Ctrl+L, esc, and then select the SDD to boot from, I get a message like welcome to Grub and there is some stuff going on in the upper edge of the screen, then a few seconds later archlinux starts, I don't get an option to select the kernel.

**Comment by genkimarshall** [comment]
It's because of graphics problems, I recommend checking out the
example grub configuration here [0]. Specifically, the setting
GRUB_GFXMODE. Edit your /etc/defaultgrub file to match.  Then re-run

# grub-mkconfig -o /boot/grub/grub.cfg

Or however you are updating your grub, but that would be what
is expected. You should then be able to reboot and see the grub menu.

[0]: https://gist.github.com/ehegnes/14b0775274d5e4c32a39

**Comment by ehegnes** [comment]
@genkimarshall that's exactly what I was thinking.

This seems to be a common issue, so I've created a [wiki page](https://github.com/raphael/linux-samus/wiki/My-GRUB2-menu-won't-display-properly,-is-glitchy,-or-blank.) to address it.

**Comment by genkimarshall** [comment]
Agreed this will be a helpful link!

**Comment by SimionKreimer** [comment]
Thank you all very much! Correcting the GRUB_GFXMODE as shown on @ehegnes wiki page totally fixed the grub and I was able to boot with the linux-samus kernel. The question I have now is if it makes sense to keep the other kernels since I'm using this one?

**Comment by raphael** [comment]
I would recommend keeping at least one other kernel. It doesn't take a lot of space and you never know :)

**Comment by raphael** [comment]
Closing this issue for now, open new ones if you have more question!
