### ISSUE TITLE
WiFi issues - lost connections

### ISSUE THREAD

**Issue by kilroykissenger** [raphael/linux-samus#131]
Wifi drops connectivity. Wifi symbol says connected but cant ping out. Happens regularly (at least once an hour) sometimes as often as every 5 mins. It has occurred across multiple networks and both 2.4 and 5 ghz. 

I know this is short on logs let me know what I can pull to help and i will pull it.

**Comment by kilroykissenger** [comment]
running pixel 2 with 4.4.5ph+ with upstart

**Comment by ehegnes** [comment]
Does this issue persist with the vanilla mainline kernel?

**Comment by kilroykissenger** [comment]
Will test that out tonight

**Comment by kilroykissenger** [comment]
testing with mainline 4.4.5. Seems to be doing the same thing but will have to test it on other networks (current network could just be garbage)

**Comment by stefanwiegmann** [comment]
could that be the same as #121? I still have that issue on 5ghz. tried to turn off powersave, but it's still happening. It only happened on the samus-kernel, not on mainline

**Comment by kilroykissenger** [comment]
It could be the same but experience the issue on both 5ghz and 2.4. I can usually resolve the issue by reconnecting but sometimes i have to disable and enable wifi all together

**Comment by ehegnes** [comment]
The only thing I can think of from this project that may have affected your interwebs is one of my first commits (f12b275) that updates the Intel® Wireless firmware. Is that firmware file up to date in `/lib/firmware/`? Alternatively, you could try some of the older firmwares listed at the [iwlwifi site](https://wireless.wiki.kernel.org/en/users/Drivers/iwlwifi).

**Comment by DerVerruckteFuchs** [comment]
There was a downgrade from 4.4-7 (kernel version 4.4.5) to 4.4.-6 (kernel 4.4.2) since there was some sleep/wake issues. I've since downgraded to the 4.4.2 based kernel to sort it out.

https://github.com/raphael/linux-samus/issues/122

I'm not sure if the same kernel (4.4.5) has WiFi issues, but I'd check to see if a downgrade to 4.4.2 will help.

I'm not having any WiFi issues myself. My only gripe is needing to restart my Network Manager service after booting up to connect to WiFi, but that's probably more to do with changed behavior in the Network Manager 1.2 update.

**Comment by raphael** [comment]
closing this as there's nothing in this repo that would affect wifi.

**Comment by chepurko** [comment]
Even though this may not be affected by this repo, does anyone with this issue have any updates on it? I have the same thing happen during long periods of use, say after every 45 minutes to 1 hour. The connection hangs while Network Manager looks like it's fine. But when I do a `systemctl restart network-manager.service` it hangs for 10 or so seconds and restarts the service, after which the connection returns. But the hangs can happen after this as well.

This has been with all kernels that I've used, and I haven't found anything online specifically about this Pixel 2 WiFi issue...

**Comment by chepurko** [comment]
And I've tried canning `network-manager` as well and switching to `wicd`. But as much as I wanted the problem to be with the dreaded Gnome Network Manager I had the same connection hangs in `wicd`, which leads to me believe it's kernel/hardware. But in either of those cases I guess there's bugger all I can do about it :stuck_out_tongue_closed_eyes:

**Comment by ehegnes** [comment]
I've never experienced anything like that. I use `wpa_supplicant` and `dhpcpd` without a manager, and it works well for me. If it really isn't a userspace issue, my suggestion would be to take a look at the [`iwlwifi` debugging page](https://wireless.wiki.kernel.org/en/users/drivers/iwlwifi/debugging), grab some logs and traces that show evidence of your issue, and post on the kernel bugzilla as mentioned in that link.
