### ISSUE TITLE
Track pad not working even after running script/temporary solution

### ISSUE THREAD

**Issue by Moovlin** [raphael/linux-samus#132]
I went about installing Ubuntu on my Chromebook Pixel LS. The install went fine, track pad didn't work initially, as expected. I ran the script, restarted, no avail. I attempted to reinstall ChromeOS because I thought I just "dun goofed" during install. I was unable to reinstall ChromeOS but upon rebooting back into Ubuntu I found my track pad suddenly worked. I restarted my computer, found the track pad didn't work again, I then tried to repair ChromeOS and the track pad works again. I have no idea what I did wrong such that the track pad isn't working unless I attempt to reinstall ChromeOS. 

I had read through the "original" issue (#73) and found that when the track pad does work, xinput reports that the trackpad is in id 9, and the touch screen in id 10. When the track pad doesn't work, the track pad is in id 10, and the screen 11. 

If I missed any helpful details, please let me know what I can include to help. I am not the most versed in a lot of the more advanced Linux commands so please pardon my stupidity.

**Comment by Moovlin** [comment]
So I guess I fixed my issue. 

I attempted to install ChromeOS, let that fail, booted into Ubuntu, then ran "./enable-atmel.sh". 
I've rebooted my computer, shut it down, and as of yet that seems to have fixed the issue. Maybe I just made a mistake during installation that caused things to break but hey, I got it working.

**Comment by raphael** [comment]
Glad to hear it's working. It has been working well for me with the latest script - had had to run it once since then after mocking with the kernel.
