### ISSUE TITLE
Getting an External Sound card working

### ISSUE THREAD

**Issue by Moovlin** [raphael/linux-samus#133]
I have a LH Labs Geek Out V1 sound card which is "plug-n-play" with Linux. Every other instillation I've just given up rather quickly but this time I decided to put some effort into getting it to work. 

This solution works on Ubuntu 16.04 LTS.

Precondition: have `alsamixer` installed. Make sure your Geek Out is properly recognized*.

What I ended up doing was plugging in my GeekOut, then launching `alsamixer`. Press `F6`, select Geek Out from the drop down. 

After the Geek Out is recognized navigate to the sound settings, and then select it like you would select either the built in headphones or speaker. Everything should work the same.  

*One of the LED's will turn blue with something is "wrong" so just keep reinserting the card until only two white LED's (one on the top 3, and the other on the bottom 4) are on.

**Comment by raphael** [comment]
This isn't an issue correct? probably would be better for this to be in the wiki. Would you mind creating an entry there and closing the issue?

**Comment by Moovlin** [comment]
Sure. I wasn't quite sure where to put it seeing as initially it was an issue and then I found a fix.
