### ISSUE TITLE
multiple toolkits (qt+gtk)

### ISSUE THREAD

**Issue by stefanwiegmann** [raphael/linux-samus#134]
Not a kernel issue, but I am curious about uniform looks of different toolkits on HiDPI screens. I posted on arch forums and did some research, but wanted to throw that out here as well.

I am using plasma and qt is scaling well for the resolution, but some apps have small (still regular?) icon sizes. How did you guys adjust fonts, icons, etc for different toolkits? Any instruction I find is either about how to adjust your "main" DE for HiDPI or how to make toolkits uniform in general, but nothing specific to higher resolutions. Some apps are gnucash, grsync, skype, gimp. Are these issue even toolkit related or purely app related?

**Comment by raphael** [comment]
I have had good success with the latest gnome, pretty much everything scales well out of the box. Some things using tcl/tk or other non-gtk toolkit do not scale (insync is the only app I use regularly that has this issue).

**Comment by wiktor-b** [comment]
I use `xrandr --output eDP1 --dpi 120` and `export GDK_DPI_SCALE=1.25`.
