### ISSUE TITLE
luks lvm linux-samus 4.4-6 stuck at "Loading initial ramdisk"

### ISSUE THREAD

**Issue by chriscrook** [raphael/linux-samus#139]
I installed a fresh archlinux using the builtin default kernel 4.5.2 and setup LVM on LUKS and everything works fine when booting that kernel - i.e, I get a passphrase prompt and can boot in afterwards.

https://wiki.archlinux.org/index.php/Dm-crypt/Encrypting_an_entire_system#LVM_on_LUKS

However when I tried booting linux-samus 4.4-6 from grub2 I'm stuck on Loading initial ramdisk.

I realize someone else had a related problem on #84 but I didn't get any error when re-running mkinitcpio.

I tried diffing my 4.5.2 kernel .config against that of linux-samus' 4.4.2 but there are obviously many differences and it's hard to pinpoint if I'm missing any particular module or builtin option.

Any ideas how I might be able to troubleshoot?

For further context, my /boot is unencrypted but my root is encrypted.  I'm afraid that since I'm not able to get past the kernel loading or initrd stage, journalctl can't help and I wasn't able to get further debugging on my console.

**Comment by reyawn** [comment]
I'm guessing that you added `i915` to MODULES for mkinitcpio as per the Linux 4.1 section on the [wiki page](https://wiki.archlinux.org/index.php/Chromebook_Pixel_2) for the Chromebook Pixel 2?

I had some weird issues booting from my USB SSD, but resolved them by changing the order of the modules loaded.

**Comment by chriscrook** [comment]
Ha, to think I've studied that page a year ago when I first bought my pixel 1 and 2 (I wasn't encrypting theirs roots at that time), I didn't think to check back - and there it was clear as day!  Suppose my google queries could have been improved by actually including +chromebook +pixel which may have gotten me to the right spot as well.

Thanks!
