### ISSUE TITLE
How can I set kernel configs ? 

### ISSUE THREAD

**Issue by keyolk** [raphael/linux-samus#140]
I need to enable CONFIG_CHECKPOINT_RESTORE and other configuration in kernel.
What I assumed, if I change the file "config" under AUR package, it may works.
But I found that every time the file .config under linux is regenerated.
I cant keep my configuration.

Could anyone inform me how can I put my configuration to kernel ?

**Comment by ehegnes** [comment]
Did you follow the steps outlined at the [ArchWiki](https://wiki.archlinux.org/index.php/Kernels/Arch_Build_System#Modifying_the_PKGBUILD)? I'm not familiar with Arch, but I can provide steps on cloning, modifying, compiling, and installing *without* the help of a package manager.

**Comment by keyolk** [comment]
It caused by my mistake. : (
I did misconfig on .config 
Thanks your advice.
