### ISSUE TITLE
Loud Fan?

### ISSUE THREAD

**Issue by rroll1** [raphael/linux-samus#143]
I'm noticing a lot of fan noise, accompanied by some pretty decent heat. I figure that the fan noise is _because_ of the heat, so I suppose these two go hand in hand.

I've been using thermald and tlp to try and reduce the horsepower of the machine to ideally reduce the heat and therefore reduce the fan noise, but I mostly just seem to be slowing down my machine without any reduction in heat or fan noise.

I do figure that due to running Arch and it being a full Linux environment (instead of CrOS/Linux) that there's probably going to be a bit more overheat, but even when I just have a couple tabs open + Pidgin I still seem to be getting pretty excessive heat / fan usage.

Has anyone come up with a solution to this? I'm asking here mostly because I don't really have any other forums to ask this on, but if this is not the proper place to ask please let me know.

Thanks!

**Comment by ehegnes** [comment]
I don't have a solution, because I don't understand what the cause of excess heat could be, but if you're interested in controlling the fan speed, look into `ectool --interface=lpc fanduty`.

What is your load average when the fans ramp up?

**Comment by rroll1** [comment]
The fans can ramp up as low as 0.8; obviously they're gonna get pretty loud at 2.0+, and that's something I entirely expect. Currently, for instance, it's at 0.44 and the fans aren't hugely loud, but I can definitely hear them.

As for ectool, where would I find that? Is that this: https://www.coreboot.org/Ectool

That's the only ectool I can find that would be at all related to anything on the Chromebook

**Comment by ehegnes** [comment]
Wow, that's a lot worse than I expected!

`ectool` is quite a gem for us Chromebook users, but it's rather difficult to get hold of. You might be able to find a packaged binary, but I prefer compiling anyway. The following instructions are modified from [this outdated but helpful guide](https://github.com/longsleep/pixel-linux/blob/master/NOTES.md#building-ectool):
```
git clone https://chromium.googlesource.com/chromiumos/platform/ec
cd ec
sed -i 's/\(COMMON_WARN =\)/\1 -Wno-error=maybe-uninitialized/' Makefile.toolchain
make BOARD=samus build/samus/util/ectool
```
\* *That `sed` line might not be necessary for you depending on your compiler and the version of `ectool`.*

`build/samus/util/ectool help` will provide you with all of the available commands. In addition to fan control, there is some functionality to provide thermal readings. You might need to use `--interface=lpc` depending on your bus configuration.

**Comment by rroll1** [comment]
Thanks! I was able to build that pretty easily. I'm pretty sure this is simply an issue of runaway process resource usage -- CrOS results in a much more controlled environment, I think, so there's less chance of a process really taking control of the machine and running away with resources. General GNU/Linux is much more open in that regard, and it's likely a result of that.

I'll play around with ectool, but likely it'll just be more important for me to apply standard Linux heat / powersaving practices to keep heat and noise down

Thanks so much for the information!
