### ISSUE TITLE
Always build with -march=broadwell?

### ISSUE THREAD

**Issue by remexre** [raphael/linux-samus#146]
If this is only ever going to run on samus machines, might as well go for that extra little bit of performance, right? I'm mostly referring to the Arch PKGBUILD here, but anything else that makes sense, too.

**Comment by remexre** [comment]
If, of course, I remember that my desktop is not a Chromebook in a fancy case.

**Comment by ehegnes** [comment]
If it's only going to run on a singe machine, you might as well build with `--march=native`, no?

**Comment by remexre** [comment]
I built it on the skylake machine; it completes a lot faster, plus I can have the kernel compiling when I'm doing the rest of the install. Ditto if an unofficial repo wants to host it

**Comment by raphael** [comment]
What exactly would you change? the compilation flags for AUR packages are typically controlled by the content of `makepkg.conf` as defined on the compilation machine.
