### ISSUE TITLE
touchpad failed after upgrade to 4.7.2

### ISSUE THREAD

**Issue by myf** [raphael/linux-samus#149]
touchpad was initially working but all of a sudden stopped. I ran https://github.com/raphael/linux-samus/blob/master/scripts/setup/touchpad/touchpad-cmt.sh and it completely stopped working. any solutions?

**Comment by myf** [comment]
found one issue, the new conf file is `etc/X11/xord.conf.d/50-touchpad-cmt-samus.conf` but there's also a `40-touchpad-cmt.conf`, getting rid of that file seem to work for now...

**Comment by raphael** [comment]
These files are experimental support for the pixel touchpad driver, that should probably be clarified.... I've had limited luck with them as well.
