### ISSUE TITLE
Touchscreen breaks with 4.8 kernel

### ISSUE THREAD

**Issue by chepurko** [raphael/linux-samus#160]
Just installed the 4.8 kernel and the touchsreen does not respond. Tried running the `enable-atmel.sh` script as well without success. After rebooting back into the 4.7.6 kernel touchscreen input came right back.

**Comment by raphael** [comment]
Just as a fyi touchscreen works fine on 4.8 for me.

**Comment by chepurko** [comment]
@raphael interesting. Will poke around later and install/reinstall/run the script to see if I can get it to work

**Comment by chepurko** [comment]
Don't think this is an issue right now with the latest release.
