### ISSUE TITLE
Screen blank at TTY after boot

### ISSUE THREAD

**Issue by DerVerruckteFuchs** [raphael/linux-samus#161]
After the 4.8 update my screen stays blank/blacked out/off until I login. The TTY login is there, but systemd's boot up messages followed by a TTY login will not show up due to the screen being blanked out until I log in. Linux mainline does not give me this issue. I'm using the modesetting driver and not using the `xf86-video-intel` for reference. I'm not sure if this is from a change from mainline 4.7 to 4.8, or if it's  specific to linux-samus4.

**Comment by nsparks86** [comment]
Unsure if it's related, but I am doing a clean install of Budgie-Remix 16.04.1, and when I install this 4.8 Kernel and reboot, I get stuck at a blank screen after the splash screen. I can't seem to switch to the other TTY screens either. Just basically stays frozen on a black screen. The bundled 4.4 seems to work fine (minus the sound).

**Comment by nsparks86** [comment]
So I was able to boot with Vanilla 4.8, but when I use this one on Budgie-Remix 16.04.1, I get a black screen after the splash screen. Can't Ctrl+Alt+1 to TTY1. It's just frozen on the black screen.

**Comment by DerVerruckteFuchs** [comment]
All I use is the default TTY login to get into i3. The login screen seems to be present and working except for the screen being blank. I can type and log in just fine. I don't know if you can just log in by just blind typing, but it's worth a shot the see if it's just an x.org or video driver thing. Another thing you could try is to switch to a different TTY and blind type a login since the TTY login screen seems to just be blank and working fine on my end. 

You may need to set it up so that your TTY login automatically starts an X session with your DE since starting X seems to "activate" the screen.

**Comment by therocco** [comment]
Same here. I am trying to install the latest 4.8 kernel on top of elementary OS Loki 0.4. This is a fresh install where I just boot up, update, and then install kernel. Upon reboot the screen fades to black when the login screen should be present and I am unable to switch to another TTY.

**Comment by myf** [comment]
Confirming blank screen at ttys, and also confirming that `startx` triggers the screen to activate. I am using `xf86-video-intel`

**Comment by DerVerruckteFuchs** [comment]
I'm thinking it might be a change in how `linux` or `linux-samus4` handles framebuffering at boot, or somehow systemd output is quieted or hidden along with a visible TTY by default with the new systemd update. I'm expecting a framebuffering issue being the more likely cause since it seems to affect TTYs in general and I'm not aware of any changes to default systemd settings concerning output at boot.

**Comment by raphael** [comment]
Yeah I'm seeing the same thing, it could be a missing flag in the kernel.

**Comment by DerVerruckteFuchs** [comment]
I updated to the new 4.8-3 release on Arch, and I got my nice systemd boot/shutdown output and TTY login screen visible again. The KMS framebuffer support you added seems to have solved the issue. Not sure if that's default in the mainline kernel, or if you're just using a workaround, but it works in the way I expect now.

**Comment by chrisrossx** [comment]
Also working for me now

**Comment by raphael** [comment]
Closing this issue, thanks for testing!
