### ISSUE TITLE
After reinstall of Arch, sound doesn't work at all

### ISSUE THREAD

**Issue by rroll1** [raphael/linux-samus#166]
I'm not sure what I did wrong here, but I reinstalled Arch and I've totally lost all sound. The kernel module does show up in lsmod:

```
[root@echo BOOT]# lsmod | grep rt5677
snd_soc_sst_bdw_rt5677_mach    16384  6
snd_soc_sst_haswell_pcm    53248  3 snd_soc_sst_bdw_rt5677_mach
snd_soc_rt5677        208896  5 snd_soc_sst_bdw_rt5677_mach
snd_soc_rl6231         16384  1 snd_soc_rt5677
snd_soc_rt5677_spi     16384  1 snd_soc_rt5677
[root@echo BOOT]# 
```

And when I open pavucontrol I can see the little volume bar bouncing up and down when I play music, but I get zero sound out of my machine.

I'm on the latest Samus kernel:

```# uname -a
Linux echo.pixel 4.8.5-ph+ #1 SMP Fri Oct 28 12:16:24 PDT 2016 x86_64 GNU/Linux
```

Am I missing something here? The appropriate lines are commented out in /etc/pulse/default.pa

**Comment by raphael** [comment]
Sounds similar to #150 - try https://github.com/GalliumOS/galliumos-samus/blob/master/usr/bin/samus-alsaenable-speakers

**Comment by rroll1** [comment]
That did it, thanks!
