### ISSUE TITLE
Can't load on chroot

### ISSUE THREAD

**Issue by bengolds** [raphael/linux-samus#174]
This may be silly, but I tried to install these drivers on a chroot Ubuntu Xenial environment. After cloning and dpkging, "uname -a" still reports kernel version 3.14. Since it's on a chroot, there's no grub environment by default; not sure if that's a problem.

**Comment by raphael** [comment]
By definition, chroot environments (or containers for that matter) use the same kernel as the host. You need to use VMs to load different kernels.
