### ISSUE TITLE
USB Device issues since 4.8.x

### ISSUE THREAD

**Issue by opticron** [raphael/linux-samus#175]
I was on 4.7.4 for a while and have since tried out 4.8.8 and 4.8.11. Both of these newer kernels appear to be missing drivers for USB serial devices (or they don't work for some reason), notably the drivers for the ch341 uart and the drivers used for connecting to Android phones.

**Comment by raphael** [comment]
OK thank you I'll take a look. Do you happen to know which flags enable these drivers?

**Comment by opticron** [comment]
For the ch341, it's CONFIG_USB_SERIAL_CH341 which looks to be built modularly. I have no idea what it would be for Android phones. I'll pull 4.8.12 and do some more testing tonight.

**Comment by raphael** [comment]
I've enabled USB serial devices with the latest release (v4.8-12) that's running the `v4.8.13` kernel. Give that a shot.

**Comment by opticron** [comment]
That gets the CH341 up and running. I retested the Android phone, but no dice on the old or new kernel, so that resolves my issues until I figure out what's going on with the phone stuff. Thanks!
