### ISSUE TITLE
Lack of CONFIG_MAGIC_SYSRQ breaks Flatpak

### ISSUE THREAD

**Issue by colemickens** [raphael/linux-samus#189]
... I think?

I tried installing some stuff via flatpak and got:
```
flatpak run org.mozilla.FirefoxNightly
Can't bind mount /newroot/proc/sysrq-trigger on /newroot/proc/sysrq-trigger: No such file or directory
```

I checked:
```
$ ls /proc/sysrq-trigger
ls: cannot access '/proc/sysrq-trigger': No such file or directory
```

And then:
```
$ zcat config.gz | grep CONFIG_MAGIC_SYSRQ
# CONFIG_MAGIC_SYSRQ is not set
```

Can `CONFIG_MAGIC_SYSRQ` be enabled?

Related issue on Flatpak: https://github.com/flatpak/flatpak/issues/643

**Comment by raphael** [comment]
Let's give that a shot, I'll build `4.10-5` with the flag enabled - thanks for the report!

**Comment by raphael** [comment]
`4.10-5` is out, it upgrades to Linux v4.10.4 and has the `CONFIG_MAGIC_SYSRQ` flag enabled.
