### ISSUE TITLE
squashfs module is missing

### ISSUE THREAD

**Issue by nskaggs** [raphael/linux-samus#192]
I get unknown filesystem type 'squashfs' trying to mount or manipulate squashfs. Can we add the kernel module?

**Comment by raphael** [comment]
Yes I'll add it to the next build.

**Comment by raphael** [comment]
v4.10-9 contains the module, please verify and close the issue thanks!

**Comment by nskaggs** [comment]
Tried with 4.11, looks like CONFIG_SQUASHFS_XZ also needs to be enabled. Specifically, I'm trying to use snap packages and running into these errors. 

kernel: squashfs: SQUASHFS error: Filesystem uses "xz" compression. This is not supported

**Comment by raphael** [comment]
bah OK I'll enable all the compression engines in the next build.

**Comment by raphael** [comment]
The latest release `v4.11-2` upgrades to Linux v4.11.1 and adds support for all the SquashFS compression engines.

**Comment by recri** [comment]
Works for me, I hit the same problem trying to install the snap for vscode, came here to complain and found it already fixed.

**Comment by raphael** [comment]
Thanks for confirming, closing the issue.
