### ISSUE TITLE
Slow charging

### ISSUE THREAD

**Issue by mbid** [raphael/linux-samus#194]
This may not be a linux-samus issue, but it may have something to do with not using the stock kernel.

My pixel charges extremely slowly, to the point that it discharges under load, even though the charger is connected. Chromeos warns about "low-power charger". I first assumed it was the charger and ordered a new one (60W), and that fixed the problem -- for a while. Now it's back to charging very slowly.

Curiously, updating chromeos (from a late-2016 version to today) fixed the problem for few days, but *again* for just a while. So I guess it is an issue of the battery chip somehow. Does somebody else experience this, or knows how to reset the chip in the way a chromeos update does?

I haven't tried a hard reset (pressing refresh + power) yet because I'm afraid that it could remove coreboot or format the hard drive. Does it?

**Comment by raphael** [comment]
I haven't seen this personally...

**Comment by colemickens** [comment]
I've not seen it either, and the fact that it occurred, then disappeared with a new charger, and then reappeared seems a bit suspect.

I have a Chromebook that regularly needs to be saluted for some weird reason... (aka, two-finger salute Refresh+Power or three-finger with Escape added)... and I can assure you that it does not format the hard drive. I'm not sure what it would mean to remove Coreboot, but I'm pretty sure it doesn't do that either... did you flash a full new coreboot on, with like a proper UEFI ala https://mrchromebox.tech/ ?

**Comment by mbid** [comment]
Glad to see that you don't have the problem, but I guess that means I'm on my own :)

Yeah sorry with the coreboot thing I meant that Refresh+Power might undo whatever I did to make the bios consider booting from other partitions. Anyway, that didn't happen.

Neither did it solve my issue though :(

**Comment by raphael** [comment]
closing this issue since it's likely not related to the kernel.
