### ISSUE TITLE
Intel Dual Band Wireless AC 7260 driver

### ISSUE THREAD

**Issue by myf** [raphael/linux-samus#196]
I start to think about it when i was trying very fast internet connection under both chromeos and archlinux for comparison. Under chromeos it goes to 160Mbps while under linux it goes between 10~90Mbps. Wonder if it's driver related. 

The last driver update was at this commit https://github.com/raphael/linux-samus/commit/205e6ee0fb7ba40fb6a681fb8d1358761d04c480 which bumped it up to version 17

however in [this intel page](https://www.intel.com/content/www/us/en/support/network-and-i-o/wireless-networking/000005511.html) it recommends to use `iwlwifi-7260-ucode-25.30.14.0.tgz` for version 4.2 and up. 

I am a bit confused about the iwlwifi driver naming scheme. wouldn't 25 be higher than 17? or is it that the previous versions 16 and 17 are from linux-firmware whereas the `25.30.14.0` is from intel? be curious to learn the answer.

if the wifi driver works much faster under chromeos there's should probably be a way to improve our version of it :)

**Comment by myf** [comment]
it looks like chromeos is still using version 16 of 7260 driver

**Comment by raphael** [comment]
Just curious: can you elaborate a little bit on how you are testing the wireless speed?

**Comment by myf** [comment]
nothing more than fast.com, I know there's a lot of factors in it but the
results are weird
