### ISSUE TITLE
EXTCON_USBC_CROS_EC should be enabled (y)

### ISSUE THREAD

**Issue by trini** [raphael/linux-samus#202]
In v4.14 EXTCON_USBC_CROS_EC is now an option and gives reliable external display support.  For that to work it needs to be built-in and that in turn requires that MFD_CROS_EC to be built in.

**Comment by raphael** [comment]
Thanks for the tip! I'll enable the flag in the next build.

**Comment by raphael** [comment]
Just released 4.14-1 which the flag enabled.
