### ISSUE TITLE
Possible to release a patch set?

### ISSUE THREAD

**Issue by MingcongBai** [raphael/linux-samus#205]
Just wondering if it would at all be possible for you to release a collection of patches made upon the upstream tree? I'm a developer of AOSC OS and will be interested in providing out-of-the-box support for Chromebook Pixel (2015), and a set of patches will make it easier to incorporate these fixes/support with newest upstream versions.

**Comment by raphael** [comment]
There is no modifications made by this repo anymore. The Kernel Linux supports all the Chromebook Pixel hardware since version 4.9.

**Comment by MingcongBai** [comment]
So is it fair to say that all that's needed are the scripts?

**Comment by raphael** [comment]
yup, well also the kernel config which is somewhat optimized for the Pixel.
