### ISSUE TITLE
hdmi adpater

### ISSUE THREAD

**Issue by chavezmx** [raphael/linux-samus#21]
has anyone tried the hdmi adpter, recently I bought one but it seems that is not working correctly, sometimes it dosent detect the external screen, first it falshes the pixel screen then it keeps black, I have to go to a tty and the images on the screen come back, but the external keeps saying not signal, other it seems getting the wrong resolution the external screen, and the pixel screen keeps black, I have to put the pixel screen as secondary to get it working. Here are some of the errors:

[   15.428569] [drm:intel_dp_complete_link_train [i915]] *ERROR* failed to train DP, aborting
[   19.734094] rt5677 i2c-RT5677CE:00: DSP VAD: enable=0, activity=1
[   32.951457] [drm:intel_dp_complete_link_train [i915]] *ERROR* failed to train DP, aborting
[  104.736914] [drm:intel_dp_complete_link_train [i915]] *ERROR* failed to train DP, aborting
[  730.540416] Raw EDID:
[  730.540422]  	5a ff ff ff 10 60 04 c0 e7 7f bf ff 08 00 00 40
[  730.540423]  	f6 fb 7e c7 00 00 84 00 ff fe ff ff 20 01 01 00
[  730.540424]  	ff ff ff 7e 01 00 00 08 ff ff ef ff 2c 21 81 00
[  730.540425]  	cf e7 6f ff 00 00 80 10 37 fd fd 77 80 00 0a 13
[  730.540426]  	4a ff ff ff 10 40 04 40 e5 7f bf ff 08 00 00 40
[  730.540427]  	f6 fb 7f c6 00 04 94 00 ff fe ff ff 20 01 01 00
[  730.540427]  	ff ff fd 7f 01 00 10 00 ff ff ef ff 28 21 80 01
[  730.540428]  	cf e7 6f fd 00 00 80 10 37 ff fd 7f 80 20 0a 13
[  730.556018] Raw EDID:
[  730.556020]  	5a ff ff ff 10 60 04 c0 e7 7f bf ff 08 00 00 40
[  730.556021]  	f6 fb 7e c7 00 00 84 00 ff fe ff ff 20 01 01 00
[  730.556022]  	ff ff ff 7e 01 00 00 08 ff ff ef ff 2c 21 81 00
[  730.556023]  	cf e7 6f ff 00 00 80 10 37 fd fd 77 80 00 0a 13
[  730.556024]  	4a ff ff ff 10 40 04 40 e5 7f bf ff 08 00 00 40
[  730.556025]  	f6 fb 7f c6 00 04 94 00 ff fe ff ff 20 01 01 00
[  730.556026]  	ff ff fd 7f 01 00 10 00 ff ff ef ff 28 21 80 01
[  730.556027]  	cf e7 6f fd 00 00 80 10 37 ff fd 7f 80 20 0a 13
[  730.571636] Raw EDID:
[  730.571639]  	5a ff ff ff 10 60 04 c0 e7 7f bf ff 08 00 00 40
[  730.571641]  	f6 fb 7e c7 00 00 84 00 ff fe ff ff 20 01 01 00
[  730.571642]  	ff ff ff 7e 01 00 00 08 ff ff ef ff 2c 21 81 00
[  730.571643]  	cf e7 6f ff 00 00 80 10 37 fd fd 77 80 00 0a 13
[  730.571643]  	4a ff ff ff 10 40 04 40 e5 7f bf ff 08 00 00 40
[  730.571644]  	f6 fb 7f c6 00 04 94 00 ff fe ff ff 20 01 01 00
[  730.571645]  	ff ff fd 7f 01 00 10 00 ff ff ef ff 28 21 80 01
[  730.571646]  	cf e7 6f fd 00 00 80 10 37 ff fd 7f 80 20 0a 13
[  730.587250] Raw EDID:
[  730.587254]  	5a ff ff ff 10 60 04 c0 e7 7f bf ff 08 00 00 40
[  730.587255]  	f6 fb 7e c7 00 00 84 00 ff fe ff ff 20 01 01 00
[  730.587256]  	ff ff ff 7e 01 00 00 08 ff ff ef ff 2c 21 81 00
[  730.587257]  	cf e7 6f ff 00 00 80 10 37 fd fd 77 80 00 0a 13
[  730.587258]  	4a ff ff ff 10 40 04 40 e5 7f bf ff 08 00 00 40
[  730.587259]  	f6 fb 7f c6 00 04 94 00 ff fe ff ff 20 01 01 00
[  730.587259]  	ff ff fd 7f 01 00 10 00 ff ff ef ff 28 21 80 01
[  730.587260]  	cf e7 6f fd 00 00 80 10 37 ff fd 7f 80 20 0a 13
[  730.587264] i915 0000:00:02.0: DP-1: EDID block 0 invalid.
[  735.479631] [drm:intel_dp_start_link_train [i915]] *ERROR* failed to enable link training
[  735.482319] [drm:intel_dp_complete_link_train [i915]] *ERROR* failed to start channel equalization
[  811.565707] haswell-pcm-audio haswell-pcm-audio: FW loaded, mailbox readback FW info: type 01, - version: 00.00, build 77, source commit id: 876ac6906f31a43b6772b23c7c983ce9dcb18a19

**Comment by raphael** [comment]
FWIW  I'm able to use the HDMI adapter just fine to connect to a 1920x1200 external monitor (the only issue being that X can't do different DPI settings for the main laptop screen and the external monitor). The only setting enabled in `modeprobe.d` is `modeset=1` which enables KMS (that is I have a file with extension `.conf` under `/etc/modprobe.d` that contains the line `options i915 modeset=1`). I doubt it's related but you could make sure you enable KMS as well.

I do see a few occurrences of:
```
[drm:intel_dp_start_link_train [i915]] *ERROR* failed to enable link training
[drm:intel_dp_complete_link_train [i915]] *ERROR* failed to start channel equalization
```
in `dmesg` but not the other errors you show above (in particular not the errors with `aborting`). Wish I could be more helpful...

**Comment by chavezmx** [comment]
I added the options, but still no luck maybe is a bug with the driver ...
I tried with a tv and 2 monitors

**Comment by raphael** [comment]
The driver is part of the kernel so I would expect the same behavior on both our machines if it had issues. I also load the `intel_agp` and `i915` modules in the initramfs stage - you could try that as well. The way I do it is by adding the line
```
MODULES="lzo intel_agp i915"
```
in `/etc/mkinitcpio.conf` (`lzo` because that's the compression algorithm I used for the kernel modules - you may not need it). You'll have to rebuild your boot img if you change that file. Ubuntu uses `update-initramfs` instead of `mkinitcpio` so ymmv.

**Comment by raphael** [comment]
Any progress on this? I'm wondering if it's related to #32, could you try adding the `i915.enable_ips=0` to your kernel command line?

**Comment by chavezmx** [comment]
No it seems that the problem persist after setting that in the kernel cmd. It's really weird maybe a debian only problem :/

I will try next week reinstall chrome os and test if it's working there, then try again with a clean debian installation.

**Comment by raphael** [comment]
I've just release v4.2-1 which runs the 4.2 kernel. Could you give that a shot?

**Comment by AdaRoseEdwards** [comment]
I am seeing the same issue on Ubuntu Gnome, currently using the latest (yesterday's) kernel release.
How do I add 'i915.enable_ips=0' to the kernel command line?

**Comment by raphael** [comment]
This page https://wiki.archlinux.org/index.php/Kernel_parameters has some great explanations on how to do that. This other page is Ubuntu specific: https://wiki.ubuntu.com/Kernel/KernelBootParameters. Closing this issue as we'll just have to wait for a upstream fix...

**Comment by AdaRoseEdwards** [comment]
I added the Kernel param 'i915.enable_ips=0' but it did not help. If it starts working due to an upstream fix i'll post again.

**Comment by rooly4** [comment]
@AdaRoseEdwards humor me on this one,

Have you tried reversing the hdmi adapter? I've been fighting with my VGA for 2 weeks without ever realizing i could turn the damn thing around. It was apparently a document issue in the tsowell repository, over here: https://github.com/tsowell/linux-samus/issues/3

**Comment by AdaRoseEdwards** [comment]
...no way. I haven't tried this but i'll give it ago next time I get access to an external monitor!
