### ISSUE TITLE
Sound problem still exist in archlinux

### ISSUE THREAD

**Issue by oowl** [raphael/linux-samus#216]
After i install linux-samus 4.16 on my chromebook pixel 2015.
When i start my computer,dmesg boot log display
```
[    3.776034] rt5677 i2c-RT5677CE:00: Can't add headphone jack gpio
[    3.776100] rt5677 i2c-RT5677CE:00: Can't add mic jack gpio
```
then i use `use-speaker-output` and `use-mic-input` provide by  'samus-scrpit' packager.
My sound card does work properly (except my mic).
But after a while, or after turning on the headset, after plugging it in a few times.
dmesg display
 ```
[  234.746910] haswell-pcm-audio haswell-pcm-audio: ipc: --message timeout-- ipcx 0x83000000 isr 0x00000000 ipcd 0x00000000 imrx 0x7fff0000
[  234.746921] haswell-pcm-audio haswell-pcm-audio: error: stream commit failed
[  234.746928]  System PCM: error: failed to commit stream -110
```
and then my computer repeat this error.Then he becomes slow，and too hot.
I can not slove this problem.

**Comment by christianbundy** [comment]
Hi @attenuation. Sorry to hear you're having trouble with the audio.

Can you try the default kernel from Arch and let me know if you still have the same problems? The linux-samus kernel makes [a few changes](https://github.com/raphael/linux-samus/wiki/Deviations-from-Vanilla-Configuration), but none of them should affect the sound support.

**Comment by oowl** [comment]
@christianbundy yes,same problem

**Comment by christianbundy** [comment]
Thanks! Can you go into alsamixer, hit F6, select the Broadwell chip, and verify that the volume on that sound device device is *also* all the way up?

Also, which desktop environment are you using? With GNOME I've had to go to the sound manager and click back and forth between the "muti-channel" and "speakers", ensuring both volumes are turned up. I'm not sure why that works, but it's saved me a few times in the past.

**Comment by oowl** [comment]
I am using plasma,
<img width="857" alt="image" src="https://user-images.githubusercontent.com/39181969/45464985-a98cbf00-b745-11e8-902c-78b8a4f86c6d.png">

Now i  use this to test it
<img width="559" alt="image" src="https://user-images.githubusercontent.com/39181969/45465015-d8a33080-b745-11e8-9fd6-7c22faf5d3dc.png">
If i face same problem,I will feedback.Thanks

**Comment by oowl** [comment]
I face same problem when i use multichannel output

**Comment by oowl** [comment]
Is this rt5677driver problem?

**Comment by ehegnes** [comment]
@attenuation after the error occurs, can you post the full output of `dmesg` in a gist? Does I/O or CPU spike when this happens?

This issue might be worth posting to the LKML, given that the driver is upstreamed and seems to cause system slowdown.

**Comment by oowl** [comment]
My firefox is very slow but io and cpu looks no problem.It is very strange.
@ehegnes 


This is htop message
![image](https://user-images.githubusercontent.com/39181969/45552474-a38d0000-b863-11e8-9752-6ba077beb12c.png)
This is iotop message 
![image](https://user-images.githubusercontent.com/39181969/45552549-da631600-b863-11e8-8a6a-8e7478a45764.png)
This is dmesg log
https://gist.github.com/attenuation/aae80a2c9fd861adcea2850ffb9a991e
You can pay attention to information related to `haswell-pcm-audio`

**Comment by oowl** [comment]
Now 
https://gist.github.com/attenuation/1126f011d70062ecd7d92d816b63384a

**Comment by christianbundy** [comment]
> This issue might be worth posting to the LKML, given that the driver is upstreamed and seems to cause system slowdown.

I second this. I'd love to help, but I don't see anything that strikes me as obvious.

**Comment by oowl** [comment]
This is the same situation as mine.
https://lkml.org/lkml/2017/9/18/54
But it seems to have not been resolved

**Comment by oowl** [comment]
This problem has appeared many times in recent days.Should I report to lkml?

**Comment by oowl** [comment]
Maybe i can give you a shell when this problem happens again

**Comment by ehegnes** [comment]
I mostly wanted to see that the firmware was loading properly with the `dmesg` log. It is. I don't understand the ASoC internals well enough to debug, unfortunately.

I'd go ahead and report it. Can't hurt to add another voice regarding the issue. If you don't get a proper response, consider reaching out to the person who authored the module in the kernel.

Original Patch (LKML): https://lkml.org/lkml/2016/8/14/207

**Comment by oowl** [comment]
@ehegnes I have already sent him an email.But his equipment is broken and cannot be maintained.

**Comment by oowl** [comment]
And i have other problem about hdmi.
When I insert the hdmi interface, dmesg's error is
```
[   35.552375] usb 1-5: new high-speed USB device number 7 using xhci_hcd
[   36.084818] usb 1-5: New USB device found, idVendor=2109, idProduct=0100, bcdDevice= 2.00
[   36.084825] usb 1-5: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[   36.084830] usb 1-5: Product: USB 2.0 BILLBOARD             
[   36.084834] usb 1-5: Manufacturer: VIA Technologies Inc.         
[   36.084838] usb 1-5: SerialNumber: 0000000000000001
[   38.059926] [drm:intel_dp_get_link_train_fallback_values [i915]] *ERROR* Link Training Unsuccessful
[   38.087035] [drm:intel_dp_get_link_train_fallback_values [i915]] *ERROR* Link Training Unsuccessful
```
My computer recognizes my hdmi, but my monitor is not lit

**Comment by oowl** [comment]
Have you encountered this problem?

**Comment by christianbundy** [comment]
@attenuation 

I've noticed some weirdness with my HDMI to USB-C adapter where the USB-C plug needs to be inserted "the right way". If I get the issues you get, I'll just flip over the plug and it'll start working just fine. At this point I've carved "this side up" on one side of the adapter, but maybe it's the same problem you're having? Hope that helps!

**Comment by oowl** [comment]
@christianbundy This is amazing.I can't believe that type c have this problem.

**Comment by oowl** [comment]
My comment for this line in `/etc/pulse/default.pa`
```
load-module module-suspend-on-idle
```

problem sloved

**Comment by oowl** [comment]
Thank you for give me help
