### ISSUE TITLE
Volume group not found issues with latest linux-image-4.16.13-ph kernel

### ISSUE THREAD

**Issue by gonzalomarcote** [raphael/linux-samus#218]
I have installed Debian 10 (buster) in my chromebook pixel 2 (2015). Sound doesn't work by default so I have tried latest linux-image-4.16.13-ph kernel from this repo, but after install it and reboot I find one issue not being able to find volume group:
```
volume group "vg01" not found
Cannot process volume group vg01
```

at (initramfs) prompt keyboard is not working to try to mount volume group.
Should this linux-image-4.16.13-ph kernel be working on debian 10?
Is there any other "new" method of having sound working on debian and this method is deprecated?

**Comment by christianbundy** [comment]
>  Should this linux-image-4.16.13-ph kernel be working on debian 10?

I'm not sure, I think most of us are using mainline now. Sorry I can't be more helpful here.

**Comment by gonzalomarcote** [comment]
Yes, after upgrading to debian 10 and using main debian kernel 4.19.0-6-amd64 now is working fine.
We can close this issue.
