### ISSUE TITLE
Volume Bug

### ISSUE THREAD

**Issue by roobyz** [raphael/linux-samus#33]
The sound volume is very low.  I found a temporary solution:  using the QasMixer, I am able to set the "hw master" volume from zero to 30. Afterward the "default master" volume is reset to "normal" and I can adjust as desired.  However, the problem is that every time I plug/unplug the headphones, lock/sleep the laptop or reboot, the volume is reset back to very low again and I have to go through the same steps again.  It would be great if the volume setting was remembered.

Cheers,
Roberto

**Comment by raphael** [comment]
Have you tried using `alsactl` to store the value after changing it? `sudo alsactl store` should do it.

**Comment by ethanmad** [comment]
If `alsactl store` doesn't work for you, try the solution proposed here: http://askubuntu.com/questions/541847/is-there-any-way-to-save-alsamixer-settings-other-than-alsactl-store

**Comment by roobyz** [comment]
I tried all the options suggested above and even updated the asound.state file directly and neither option stored the volume result.  In fact, the "hw master" volume always jumps back to zero immediately after I leave the hw menu.  Could be why it keeps storing the zero value.

**Comment by ethanmad** [comment]
It might be possible to set volumes on login or xinit by adding a systemd unit or adding a command to xinitrc. Not a solution, but a good enough workaround if it works. (I haven't tried either one.)

**Comment by raphael** [comment]
Sounds like there's something running resetting the volume, maybe your DE?

**Comment by roobyz** [comment]
I'm running Gnome 3.16 and haven't found anyway to adjust the hw master volume.  It looks like Gnome is only affecting the pulse volume.  I'll do some searching.

**Comment by colemickens** [comment]
Interesting. My master volume is set to 100% and I still find the headphone output to be quite low. Probably much healthier for my ears, but disappointing enough that I switch to consuming the content on my phone so that I can have some volume. It's low enough that it's not really usable on the bus, etc.

Anything else to check? I even built qastools and checked qasmixer but it said master was at 100%. (And I'm obviously making sure that VLC is at 100%, and that my output in Pulse is set to 100%)

**Comment by ethanmad** [comment]
I've gotten headphone volume loud enough (without extra software
configuration) that I can play drums with them, but that might be due to
the amp and headphones I use.

**Comment by raphael** [comment]
@colemickens is that with restoring the latest alsa state found in this repo?

**Comment by colemickens** [comment]
Cloned the whole repo on a wired server, tar'd firmware/scripts, copied to my Pixel2, extracted, ran `cd setup; ./sound.sh`. Lost sound until reboot. And now I have appropriately-volumed headphones. Thanks!

**Comment by raphael** [comment]
nice! what about speakers? it seems that last update fixed headphones but moved the problem to the speakers (reverse left-right and not as loud as it should be).

**Comment by ethanmad** [comment]
My speaker channels are reversed. Volume seems OK, but I'm not sure how loud it should be.

**Comment by colemickens** [comment]
I will agree with everything @ethanmad said. Seems like it *might* be a touch quieter than before I updated the stored state today, but I can't say for sure. The channels are definitely reversed now (I assume but never specifically checked that they were correct before).

**Comment by roobyz** [comment]
Hi All, my left-right is correct on headphone and speaker. My "normal" volume level is at 100%.  
To "normalize" the volume, go into the mixer and:
* switch to **bdw-rt5677** and set Master to 100% then
* switch back to **default** and set Master as desired.

At this point the volume adjustment works as expected and the "normal" volume level is at around 40%. However when I plug/unplug the headphones, I need to repeat the above steps.

**Comment by ethanmad** [comment]
@roobyz Should those steps fix channel positions, too? I'm not noticing a difference in volume, but my channels are still reversed.

**Comment by roobyz** [comment]
My channel positions are actually correct, so I can't be certain, but I believe my steps only resolves the volume issue.

**Comment by defunkt1721** [comment]
After new patch, laptop speaker volume is alright however the volume from the headphone jack is really low even when bumped up above 100%. 

Is it possible to revert my audio config to the one from your previous kernel update?

**Comment by raphael** [comment]
Yes simply restore the alsa state from https://github.com/raphael/linux-samus/blob/cc3badb3b2bd20502f1098286b8d1be981e06d94/scripts/setup/alsa/asound.state
`alsactl restore -f asound.state`
Sorry for the back and forth on this, tryin to figure out the right tweaks. The chromium sound daemon CROS seem to update the alsa settings dynamically when plugging in earphones. Need to blend the two or create UCM rules, working on it...

**Comment by defunkt1721** [comment]
That's alright! Thanks for all the hard work you're putting into this. 

It's my first time messing with kernels and whatnot so the best thing I can do in order to contribute at the moment would be to report issues like this and provide suggestions :)

**Comment by raphael** [comment]
I think I finally managed to get an ALSA state that would work for both the speakers and headphones. Would you mind giving the latest `asound.state` a shot?
```
cd linux-samus/scripts/setup/alsa
sudo alsactl restore -f asound.state
```

**Comment by roobyz** [comment]
Gosh... that didn't fix it.  I got the most horrendous loud screech and had to hard reset the machine.  Like defunkt1721 mentioned, it seemed like the change prior to this one did work on the normal volume but the headphones were still low.

**Comment by raphael** [comment]
ugh I'll check it out. I also put two other state in the same directory "speakers.state" and "headphones.state" I guess for how restore one or the other depending on which you want to use...

**Comment by Ivan0xFF** [comment]
So, I moved headphones.state and speakers.state into /opt/samus-alsa/ and modified /etc/acpi/handler to include this:

    jack/headphone)
        case "$3" in
            plug)
                logger "headphone plugged"
                alsactl restore -f /opt/samus-alsa/headphones.state
                alsaucm -c bdw-rt5677 set _verb HiFi set _enadev Headphone
                ;;
            unplug)
                logger "headphone unplugged"
                alsactl restore -f /opt/samus-alsa/speakers.state
                alsaucm -c bdw-rt5677 set _verb HiFi set _disdev Headphone
                ;;
            *)
                logger "ACPI action undefined: $3"
                ;;
        esac
        ;;

It's working pretty well for me. Might be a workaround worth using until we have a merged alsa state file.

**Comment by raphael** [comment]
nice! would you mind creating a PR to update the README with this?

**Comment by c0z3n** [comment]
second user confirming @roobyz 's loud demon screech of death using the most recent asound.state. Scared the piss out of me the first time.

will try the scripted solution by @Ivan0xFF tomorrow.

**Comment by raphael** [comment]
I think I may have finally got it. Please give the latest `asound.state` a spin. Hopefully it won't be as scary.

**Comment by c0z3n** [comment]
Just tried the most recent `asound.state`, no more screeching demon laptop but the headphone volume still seems lacking, it doesn't seem any different than before. only a fraction of the volume they can achieve using `headphones.state`

**Comment by roobyz** [comment]
Same as c0z3n. Doesn't seem to be a difference.

**Comment by recri** [comment]
I had problems with the /etc/acpi hacks.  First, Ubuntu acpid doesn't install a handler.sh script, so I hand made plug/unplug events and handler scripts.  Second, alsaucm fails because there is no bdw-rt5677 ucm descriptor installed, so I copied scripts/setup/ucm/ into /opt/samus-alsa and used  ALSA_CONFIG_UCM=/opt/samus-alsa/ucm/ alsaucm ... in the handler.sh scripts.  That made the headphone/speaker switch work, and volume seems good, too.

I had tried installing the bdw-rt5677 ucm descriptors in the permanent location (/usr/share/alsa/ucm/) before, but they didn't work very well there.  I don't see them being installed by sound.sh.

**Comment by ethanmad** [comment]
Anyone else not getting any sound out as of the last one or two updates?
Seems like my default card in alsa switched to `pulseaudio`, which might be
the problem.

**Comment by earl-ducaine** [comment]
A bit off topic, but does anyone know if the sound stuff is being integrated in any of the upstream Linux branches.  If not (I've been watching periodically and haven't seen it, but I'm not that familiar with the Linux dev process.) is there a technical reason why integration isn't proceeding or is it just a resource issue, i.e. someone need to pick it up and shepherd it through?

**Comment by aa0na** [comment]
i'm using arch linux.  installed the kernel, required packages for arch linux (pulseaudio pulseaudio-alsa pavucontrol alsa-utils acpid and starting acpid), and then the sound.sh script.

pavucontrol shows sound playing on bdw-rt5677 under both output and playback but no sound is coming out.  under output, if i toggle between headphones and speaker, sound comes out.  this lasts until a reboot then it's back to where it was.  just some info.

**Comment by wulvyrn** [comment]
re-install today.  output and playback are defaulting to hdmi.
changing to speaker on playback and then under output, i had to toggle from speakers to headphones and back to speakers for sound to play.

**Comment by roobyz** [comment]
With the latest 4.4-3 update, I think it is safe to say that this one is closed. Cheers!
