### ISSUE TITLE
system freezes after 4.2 upgrade

### ISSUE THREAD

**Issue by myf** [raphael/linux-samus#39]
I start to notice that my system would stop responding (except for mouse movement) a couple of times after the 4.2 upgrade. Cannot access anything else since keyboard was not responding. I wonder if anyone else has the same problem?

**Comment by raphael** [comment]
No freezes here. Are these temporary? do you have to reboot? anything in `dmesg` or `/var/log/syslog` or equivalent?

**Comment by myf** [comment]
actually you are right, i cannot recreate this bug. will investigate when this happens again and reopen.
i do have to reboot afterwards.
