### ISSUE TITLE
Failure to boot kernel 

### ISSUE THREAD

**Issue by cowlicks** [raphael/linux-samus#40]
I'm running currently on debian testing on a pixel 2 LS. I installed the packages in `build/debian`, rebooted. But when I select the new kernel, I just get a black screen, no response from anything at all.

My drive is encrypted, which may be effecting things.

**Comment by raphael** [comment]
Sounds similar to issue #17 and #27. Could you try going through https://wiki.archlinux.org/index.php/Boot_debugging to troubleshoot?

**Comment by cowlicks** [comment]
None of the logging params worked. None of the kernel parameters from the "intel video chips" section worked, I tried `nomodeset`, `video=SVIDEO-1:d`, and `i915.modeset=0`.

I'm not sure what else to try.

**Comment by genkimarshall** [comment]
Sorry for the drive-by comment, but I also experienced the same message about failure of loading ramdisks as was in #27 (commenting here b/c that one was closed, and it is referenced above).
Anyway, I downgraded my kernel to release 4.13-1, and it successfully booted up.
I know this isn't a particularly helpful comment, but I just thought I would recommend to @cowlicks to try installing release 4.13-1 (i.e. clone this repo, checkout commit 874d0173e707e4b4392a9c6ac8e1de1cd7660dbc, and build), to see if that works.
Just saying because of "not sure what else to try".
I would normally go into more details/debugging about what went wrong. Hopefully it helps in the meantime.

**Comment by raphael** [comment]
That's interesting because the only difference config-wise between these releases is adding HID modules in 4.2 which shouldn't affect anything related to booting... dunno

**Comment by genkimarshall** [comment]
Hmm, it totally could be that the re-install itself fixed my problem, independent
of which version it actually was. Not sure.

**Comment by cowlicks** [comment]
I don't actually get a "failure loading ramdisks" error. I'll try a different kernel version. @raphael I would just run `patch.sh` on [`874d017`](https://github.com/raphael/linux-samus/commit/874d0173e707e4b4392a9c6ac8e1de1cd7660dbc)?

**Comment by raphael** [comment]
You can just compile the pre-patched kernel in `build/linux-patched`.

**Comment by raphael** [comment]
@genkimarshall that's my feeling too. Either that or something (the boot loader?) needs to be told about the new kernel version.

**Comment by cowlicks** [comment]
I'm using grub, it detects the new kernel. I tried `sudo update-grub` to no avail.

**Comment by raphael** [comment]
I've released a new version and tweaked config option in the hope to make the kernel more compatible. I'm shooting in the dark though so don't set your hopes too high ;)

**Comment by cowlicks** [comment]
So I think was a combination of two problems. My "enter crypt password" screen was not working. And my keyboard map was not being applied at boot time. So I was entering my password with the wrong keyboard map. And not getting anywhere. However I can now boot the kernel.

**Comment by cowlicks** [comment]
I'll try the new release

**Comment by cowlicks** [comment]
I get this error when I run the `sound.sh` script
```bash
➜  setup git:(master) bash sound.sh 
Setting sound card UCM verb
ALSA lib main.c:344:(execute_sequence) unable to open ctl device 'hw:bdwrt5677'
ALSA lib main.c:1547:(set_verb_user) error: failed to initialize new use case: HiFi
alsaucm: error failed to set _verb=HiFi: No such device
!!Failed to set UCM verb, make sure 'alsaucm' is installed
```

**Comment by cowlicks** [comment]
Following the steps in the "enabling sound step-by-step" section I get the part where I list sound devices. And I don't see the non-hmdi one
```bash
➜  ~  aplay -l 
**** List of PLAYBACK Hardware Devices ****
card 1: HDMI [HDA Intel HDMI], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: HDMI [HDA Intel HDMI], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: HDMI [HDA Intel HDMI], device 8: HDMI 2 [HDMI 2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

**Comment by cowlicks** [comment]
Some stuff from dmesg
```bash
➜  ~  dmesg  | grep rt5677
[   11.731644] bdw-rt5677 bdw-rt5677: ASoC: CPU DAI System Pin not registered
[   12.964096] bdw-rt5677 bdw-rt5677: ASoC: CPU DAI System Pin not registered
```

**Comment by cowlicks** [comment]
Going over your debugging recommendations [here](https://github.com/raphael/linux-samus/issues/30)
```bash
➜  ~  lsmod | grep bdw 
snd_soc_sst_bdw_rt5677_mach     7785  0
snd_soc_sst_haswell_pcm    43345  1 snd_soc_sst_bdw_rt5677_mach
snd_soc_rt5677        162753  1 snd_soc_sst_bdw_rt5677_mach
snd_soc_core          124122  4 snd_soc_rt5677,snd_soc_rt5677_spi,snd_soc_sst_haswell_pcm,snd_soc_sst_bdw_rt5677_mach
➜  ~  ls /dev/snd 
by-path  controlC1  hwC1D0  pcmC1D3p  pcmC1D7p  pcmC1D8p  seq  timer
➜  ~  aplay -l
**** List of PLAYBACK Hardware Devices ****
card 1: HDMI [HDA Intel HDMI], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: HDMI [HDA Intel HDMI], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: HDMI [HDA Intel HDMI], device 8: HDMI 2 [HDMI 2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
➜  ~  pavucontrol

pulseauido server not found and this fails
```

**Comment by cowlicks** [comment]
It looks like my "sound devices" are not properly installed. Not sure what to do about this.

**Comment by cowlicks** [comment]
I installed the debian package "`linux-firmware-nonfree`" but got nothing new in `/dev/snd`

I'm out of ideas for now

**Comment by hieu2ueih** [comment]
@cowlicks If you follow the steps on issue #13 by moving the Intel firmware to the /lib/firmware/intel and editing the line "load-module module-alsa-sink device=hw:0,0" to /etc/pulse/default.pa it should resolve your issues.

**Comment by raphael** [comment]
Did @hieu2ueih suggestion work for you @cowlicks?

**Comment by cowlicks** [comment]
Yes, thanks @raphael @hieu2ueih !!
