### ISSUE TITLE
Privacy Light does not turn on when using webcam

### ISSUE THREAD

**Issue by colemickens** [raphael/linux-samus#41]
Wouldn't have thought this was possible, but the privacy light doesn't activate when using the webcam.

I guess I'm assuming there's a privacy light. I remember it on the original model, I assume there's one on the 2015 model as well.

**Comment by raphael** [comment]
Bah it turns on for me (just running `cheese`).

**Comment by colemickens** [comment]
Hm, every attempt today is turning it on.

I'll have to pay more attention to when it doesn't come on...

**Comment by colemickens** [comment]
I'll close this until I get more information, sorry for the noise.
