### ISSUE TITLE
chromeos sysfs entries

### ISSUE THREAD

**Issue by c0z3n** [raphael/linux-samus#43]
Various sources online indicate that in linux kernels >=4.1 have a sysfs entry implemented talking to the chromebook embedded controller, to control the lightbar, etc., at `/sys/devices/virtual/chromeos/cros_ec/`. I'm basing this on [this patch on the mailing list](http://lkml.iu.edu/hypermail/linux/kernel/1504.3/00827.html).

However, these sysfs entries don't exist on my installation. Is this implemented in the kernel distributed in this repository? has anyone else got these sysfs entries or been able to control their lightbar using the 4.2 kernel from this repo? If yes, what do I need to do to enable/install these sysfs entries and/or is there a substitute for controlling the lightbar, etc.?

I am running Xubuntu 15.04 on a 2015 chromebook pixel LS, with the linux kernel from this repo. let me know if there's any outputs from my machine I should provide.

Thanks for any help!

**Comment by raphael** [comment]
Unfortunatly the driver won't load on Pixel 2, only on Pixel 1. If you're feeling brave you could try patching https://github.com/torvalds/linux/blob/master/drivers/platform/chrome/chromeos_laptop.c#L518-L522 to change the product name to "Samus" (instead of "Link" = Pixel 1).

**Comment by c0z3n** [comment]
Ah, that's a shame. Thanks for the information.
