### ISSUE TITLE
Keyboard light doesn't turn on after a suspend.

### ISSUE THREAD

**Issue by qivittoq** [raphael/linux-samus#46]
My keyboard light stop recently from turning on again after a suspend.

**Comment by legospacy** [comment]
I've also noticed this, along with not being able to set the keyboard backlight anymore (I wrote my own script to use the `/sys/class/leds/chromeos::kbd_backlight/` interface). I noticed in 730e8a6d5e7e7b9cabbb89e65804892af939f229 that `CONFIG_LEDS_CHROMEOS_KEYBOARD` was unset. Maybe this is why?

**Comment by nevetas** [comment]
Just installed the new version now but keyboard back-light settings  still not working for me?

**Comment by raphael** [comment]
Issue fixed in release 4.2-6.
