### ISSUE TITLE
video debian jessie

### ISSUE THREAD

**Issue by chavezmx** [raphael/linux-samus#47]
This is not an issue with the kernel, but it may provide a bad user experience to those of us that use debian, just to let you know that the default package xserver-xorg-video-intel is too old and doesn't have support for our graphics, so in the gnome details is shown as gallium graphic driver. To solve this problem use the following instruction to upgrade, and you will see a huge difference in performance with videos.

add this to your sources.list:
deb http://http.debian.net/debian jessie-backports main

and install the package:
apt-get -t jessie-backports install "xserver-xorg-video-intel"

sorry if this is not the way to report this...

**Comment by raphael** [comment]
Thanks, this is good information. Would you mind creating a PR that updates the README with it?
