### ISSUE TITLE
maxtouch.cfg

### ISSUE THREAD

**Issue by caesee** [raphael/linux-samus#48]
maybe it`s not a issue;
 When i run dmesg;
There are some warnings 
eg.
[    1.301705] iwlwifi 0000:01:00.0: Direct firmware load for iwlwifi-7260-15.ucode failed with error -2
[    1.301726] iwlwifi 0000:01:00.0: Direct firmware load for iwlwifi-7260-14.ucode failed with error -2
[    1.369680] atmel_mxt_ts i2c-ATML0001:01: Direct firmware load for maxtouch.cfg failed with error -2

maybe it`s lack of drivers .

**Comment by raphael** [comment]
I have seen these and as far as I can tell they don't cause issues (the iwlwifi-7260-13.ucode firmware ends up being loaded and the touchpad works just fine.)
