### ISSUE TITLE
no joystick support

### ISSUE THREAD

**Issue by recri** [raphael/linux-samus#49]
Why did you disable joystick support in your "optimized" kernel?  It did not make the kernel run faster, and I wasted a day figuring out why none of the online tutorials for enabling a joystick worked.
```
diff .config.old .config
2015c2015
< # CONFIG_INPUT_JOYDEV is not set
---
> CONFIG_INPUT_JOYDEV=m
2017c2017
< # CONFIG_INPUT_EVBUG is not set
---
> CONFIG_INPUT_EVBUG=m
2057,2058c2057,2094
< # CONFIG_INPUT_JOYSTICK is not set
< # CONFIG_INPUT_TABLET is not set
---
> CONFIG_INPUT_JOYSTICK=y
> CONFIG_JOYSTICK_ANALOG=m
> CONFIG_JOYSTICK_A3D=m
> CONFIG_JOYSTICK_ADI=m
> CONFIG_JOYSTICK_COBRA=m
> CONFIG_JOYSTICK_GF2K=m
> CONFIG_JOYSTICK_GRIP=m
> CONFIG_JOYSTICK_GRIP_MP=m
> CONFIG_JOYSTICK_GUILLEMOT=m
> CONFIG_JOYSTICK_INTERACT=m
> CONFIG_JOYSTICK_SIDEWINDER=m
> CONFIG_JOYSTICK_TMDC=m
> CONFIG_JOYSTICK_IFORCE=m
> CONFIG_JOYSTICK_IFORCE_USB=y
> CONFIG_JOYSTICK_IFORCE_232=y
> CONFIG_JOYSTICK_WARRIOR=m
> CONFIG_JOYSTICK_MAGELLAN=m
> CONFIG_JOYSTICK_SPACEORB=m
> CONFIG_JOYSTICK_SPACEBALL=m
> CONFIG_JOYSTICK_STINGER=m
> CONFIG_JOYSTICK_TWIDJOY=m
> CONFIG_JOYSTICK_ZHENHUA=m
> CONFIG_JOYSTICK_DB9=m
> CONFIG_JOYSTICK_GAMECON=m
> CONFIG_JOYSTICK_TURBOGRAFX=m
> CONFIG_JOYSTICK_AS5011=m
> CONFIG_JOYSTICK_JOYDUMP=m
> CONFIG_JOYSTICK_XPAD=m
> CONFIG_JOYSTICK_XPAD_FF=y
> CONFIG_JOYSTICK_XPAD_LEDS=y
> CONFIG_JOYSTICK_WALKERA0701=m
> CONFIG_INPUT_TABLET=y
> CONFIG_TABLET_USB_ACECAD=m
> CONFIG_TABLET_USB_AIPTEK=m
> CONFIG_TABLET_USB_GTCO=m
> CONFIG_TABLET_USB_HANWANG=m
> CONFIG_TABLET_USB_KBTAB=m
> CONFIG_TABLET_SERIAL_WACOM4=m
2165c2201,2205
< # CONFIG_GAMEPORT is not set
---
> CONFIG_GAMEPORT=m
> # CONFIG_GAMEPORT_NS558 is not set
> # CONFIG_GAMEPORT_L4 is not set
> # CONFIG_GAMEPORT_EMU10K1 is not set
> # CONFIG_GAMEPORT_FM801 is not set
```

**Comment by raphael** [comment]
I guess I didn't realize that using a joystick was even possible... I'll enable the options in the next build (leaving this issue opened until I do so).

**Comment by recri** [comment]
This is what happens when you try to outwit the hive mind and configure a kernel based on unaugmented common sense, ;-)

**Comment by raphael** [comment]
aaaah but that way we all get to learn ;)
Latest release upgrades Linux to 4.2.4 and should fulfill all your joystick needs.

**Comment by recri** [comment]
Don't know where you put the changes, they're not in the 4.2.4 linux-samus/build/linux/.config:

# CONFIG_INPUT_JOYDEV is not set

And they're not in the binary either.

**Comment by raphael** [comment]
I had enabled `CONFIG_INPUT_JOYSTICK` and all the joystick drivers (`CONFIG_JOYSTICK_xxx`). I'll build another release also enabling CONFIG_INPUT_JOYDEV.

**Comment by raphael** [comment]
The latest release also enables CONFIG_INPUT_JOYDEV (and upgrades to Linux 4.2.5).

**Comment by recri** [comment]
That works, thanks.
