### ISSUE TITLE
audio configuration doesn't seem to support external micrphones via the headset/combo jack

### ISSUE THREAD

**Issue by c0z3n** [raphael/linux-samus#52]
as described in the title, the microphone input on the headphone/headset/combo jack doesn't seem to be supported by the current audio configuration. is this something other people have gotten working based on this repo?

**Comment by raphael** [comment]
Have you tried tweaking the controls with `alsamixer`? I don't have a mic to try it out but it sounds like an issue with a control being too low or not enabled in alsa.

**Comment by c0z3n** [comment]
I have tried poking through alsamixer, and I haven't found anything that works. even when I've got a mic plugged in there, all the microphone inputs report the signal from the pixel mic

**Comment by raphael** [comment]
One thing you could try is to boot into ChromeOS (obviously that requires that you can do that) and use `alsactl` there to capture the alsa state after you connect your headphones (using `alsactl store`). Restoring that state in Linux should then enable the mic (assuming it works in ChromeOS).

**Comment by raphael** [comment]
Closing for now, reopen if the above doesn't help.
