### ISSUE TITLE
Release Tarballs

### ISSUE THREAD

**Issue by jwhipp** [raphael/linux-samus#53]
Can we get release tarballs in a separate area?

Two issues generating this request:

1. The github download rate is horrible for the whole repo

2. Allows us to download just the files we need for our respective distro

Thanks for all the hard work!

**Comment by raphael** [comment]
You can download releases from https://github.com/raphael/linux-samus/releases is that not what you are after?

**Comment by jwhipp** [comment]
For some reason, I didn't see em.   My bad.
