### ISSUE TITLE
Touchpad laggy, tap click and drag engaging when it shouldn't be

### ISSUE THREAD

**Issue by jwhipp** [raphael/linux-samus#56]
Having issues with the touchpad, the pointer is laggy, has a lot of delays and stickiness.   Also, if tap to click is turned on, I get random dragging of objects like it's stuff in a hold-click state.

Anyone else getting this weirdness? I am on Ubuntu 15.10 x64 with the 4.2.5ph+ kernel.

**Comment by ethanmad** [comment]
I haven't noticed lag, but I do get issues with dragging when tap-to-click
on.

It's probably all fixable by messing with the touchpad settings (Synaptic
file, at least in Arch), but I haven't tried hard enough to get something I
really like. I might turn tap-to-click off and be done with it.

If you do manage to get a good Synaptic profile, please do share it.

**Comment by AdaRoseEdwards** [comment]
I run this on startup 

```
synclient TapButton2=2 # 2 finger middle click
synclient TapButton3=3
synclient FingerHigh=35 # Sensitivity
synclient FingerLow=29 # Sensitivity
```

These finger high and finger low settings are better and work well for me but are still a little sensitive for my partner.

**Comment by jwhipp** [comment]
The other thing that's a little strange is the menu keeps open and closing while the mouse is moving around on it's own.   Anyone seeing this?

**Comment by jwhipp** [comment]
My system took an update to linux-firmware, when I boot to the stock 4.2 kernel, the craziness stops.  I'm going to update to the latest kernel and firmware posted in the repo and remove stock 4.2 and see if that fixes the issues.

**Comment by jwhipp** [comment]
So it appears that is was the linux-firmware package being updated from the ubuntu repos caused the craziness I was seeing.    I'm wondering if it's better to pull the stock kernels out completely.

Have you considered doing a PPA?

**Comment by raphael** [comment]
I have, see branch "ppa". However I don't run Debian/Ubuntu so can't easily test. Would be awesome If someone could pick up the work on that branch and maintain a ppa. Where I had stopped was that the PPA would fail to build for strange reasons. Not being able to build the source package on my box made it pretty much impossible to debug.

**Comment by raphael** [comment]
closing this issues as it seems you found the problem.
