### ISSUE TITLE
Touchpad fails after resume from suspend - requires 3 finger salute to reset

### ISSUE THREAD

**Issue by colemickens** [raphael/linux-samus#57]
Hi.

I'm seeing this behavior after the most recent update from AUR.

Sometimes (a few times a day at least), I will open my laptop and find my touchpad unresponsive. Cursor doesn't move. I suppose I haven't tested to see if click events work.

Rebooting is not sufficient. At least, a single reboot isn't.

My workaround is to "Three Finger Salute" (Esc + Refresh + Power) and then power off, and then normal boot.

**Comment by raphael** [comment]
Hmm I noticed that issue too actually but had blamed it on my previous experiment with 4.3 (where the touchpad just didn't seem to work at all). Just to confirm: this is with 4.2-9?

**Comment by c0z3n** [comment]
This sounds similar to an issue I have been having, where sometimes on resume the trackpad will not be working, but the mouse cursor on the screen will be tweaking out, jittering, clicking randomly etc. a hard reboot does seem to resolve it for me though (holding the power button until the laptop shuts down and then rebooting)

**Comment by colemickens** [comment]
So, the day I reported this, I had this problem almost every time I resumed. Yesterday I experienced in a couple times, with numerous times not hitting it.

Today, I've resumed probably 5 times already without hitting the issue.

```
$ uname -a
Linux pixel 4.3.0-1ph #1 SMP Tue Nov 10 00:43:03 PST 2015 x86_64 GNU/Linux
```

@raphael your comment makes me wonder... should I not be on 4.3? I didn't do anything special other than the usual `yaourt -Syua`.

**Comment by ethanmad** [comment]
@colemickens The [latest release](https://github.com/raphael/linux-samus/releases/tag/v4.2-9) is based on Linux 4.2.6. I think if you do another update, you'll get that release.

P.S. If you haven't previously tried `pacaur`, I find it a lot nicer than `yaourt` because all confirmations come before the downloads start, so you can leave computer to update without constant attendance.

**Comment by raphael** [comment]
I have had a number of different issues with 4.3 including non working touchpad, sleep and issues with external monitors. So I reverted to 4.2.6 in my latest release. The branch v4.3 uses the 4.3 source tree, the plan is to keep it up-to-date with the latest upstream and hopefully merge that into master once things are stable.

**Comment by colemickens** [comment]
Yes, running `yaourt -S linux-samus4` has caused a downgrade to `4.2.6-9ph`. (Though, the first reboot caused a non-working trackpad... I'll assume it's bad state left over from 4.3 and hope it's okay for the rest of the day).

Thanks also for the details about 4.3.

**Comment by raphael** [comment]
Have you had the issue since downgrading? if not please close this issue, thanks!

**Comment by colemickens** [comment]
Yes, I had meant to close this last night. I had to reinstall Arch over the weekend (it forgot dev_boot_usb and dev_boot_legacy somehow). Everything was painless. Fully working audio with accelerated graphics. Great stuff, thanks.

**Comment by raphael** [comment]
nice! always good to hear :)

**Comment by damianb** [comment]
Just to note, I've randomly hit this off and on for a while now, and I've been on 4.2-8.  Randomly on boot or resume touchpad just freaks out, no input is accepted and the cursor is flying all over the place.  Keyboard doesn't work for all of this duration either.

I'm wondering if this is the touchpad or if this is the touchscreen; I'm able to control the mouse via both, so.

**Comment by raphael** [comment]
I remember experiencing the same behavior but it has been a while since I've seen it. Try upgrading to 4.2-10.

**Comment by damianb** [comment]
Should mention that I did encounter it recently on 4.2-10.  Notice you put up 4.3 - will update when I get a chance and keep my eyes open.
