### ISSUE TITLE
Touchpad recognized by kernel, but no output from device

### ISSUE THREAD

**Issue by ehegnes** [raphael/linux-samus#58]
Although the Atmel maXTouch Touchpad is recognized by the kernel...
```shell
dmesg | grep -i touchpad                                                                                                      0
[    5.098145] input: Atmel maXTouch Touchpad as /devices/pci0000:00/INT3432:00/i2c-7/i2c-ATML0000:01/input/input14
```
...my mouse will not move. But wait! I have more evidence than the uneventful dragging of my finger on the touchpad.

Outputs from `xinput --test` and `evtest` are blank when they should be logging input events. `/var/log/Xorg.0.log` confirms that the touchpad is recognized by the X server and that the `cmt` driver is loaded.

I am using the v4.3-1 release (5edd2cb) with the [Gentoo patchset](https://dev.gentoo.org/~mpagano/genpatches/trunk/4.3/) applied.

I'm particularly confused, because I thought that this touchpad was supported by the mainline kernel. A [relatively recent patch](https://lkml.org/lkml/2015/4/7/1112) that includes the usage of [`samus`-specific firmware](https://chromium.googlesource.com/chromiumos/overlays/board-overlays/+/master/overlay-samus/chromeos-base/chromeos-touch-config-samus/files) is all I can find that may be of interest, as this new code is not included in [`atmel_mxt_ts.c`](https://github.com/raphael/linux-samus/blob/v4.3-1/build/linux/drivers/input/touchscreen/atmel_mxt_ts.c).

I'm glad to share any potentially helpful output from my computer upon being prompted.

**Comment by raphael** [comment]
I had the same issue (amongst others such as https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1488719 and issues with power management) with 4.3. The latest release (4.2-9) uses 4.2.6 and everything seems to work just fine there. There are later commits to `atmel_mxt_ts.c` that undo some of the changes you point to, that's probably why you don't see these changes in the 4.3 tree (see https://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/log/drivers/input/touchscreen/atmel_mxt_ts.c). So TL;DR I'd recommend sticking with 4.2 for now. Hopefully the stable branch of 4.3 will iron out the kinks there.

**Comment by ehegnes** [comment]
Thank you for the pointer! So, I was just about to get on here and complain about framebuffer issues (solved by building `i915` into the kernel as opposed to as a module), kernel panic issues, and self-detected CPU stalls on v4.2-9. I figured I'd regress versions until something worked. But miraculously, my touchpad now works in the 4.3 kernel I previously had installed. Hmph...I'll do some digging and try to figure out why this is.

@raphael I'm hijacking my own issue, but what are these power management issues you speak of? I haven't yet done any power tweaking, and I'm currently drawing 10 Watts running a very minimalistic DWM on full screen brightness. This seems maybe rather high, considering I used to be able to draw 5W consistently on my old C720P Chromebook.

**Comment by ehegnes** [comment]
Okay, at least I now have something reproducible (for myself):

1. Make v4.3 and install
2. Make v4.2 and install
3. Touchpad works in v4.3
4. Make v4.3 and install
5. Touchpad doesn't work in v4.3

I originally thought that maybe some modules were sticking around from v4.2 when I booted into v4.3, but that doesn't make sense. Modules are partitioned by version as such `/lib/modules/<kernelversion>`.

Anybody have some kind of brilliant insight?

**Comment by raphael** [comment]
By power management issues I meant issues with sleep: closing the laptop lid would not make it go to sleep.
I wonder if the behavior you are seeing has something to do with the kernel modules being loaded? Not sure what "install" entails but is it possible that it's causing modules to get unloaded/loaded?

**Comment by ehegnes** [comment]
Ah, I don't have `acpid` setup to detect lid closing anyway, but `acpi_listen` seems to log `button/lib LID  {close,open}` just fine.
Sorry for the ambiguous reference to "install". What I mean is the standard procedure for installing unpackaged kernels:
```bash
$ make -j4  -l3.5
$ make modules_install
$ make install
```
I can intermittently check my loaded modules, but I'm truly stumped, now that my touchpad does't work this morning on the same kernel it worked on a few hours ago (with no changes having been made to system configurations).
This might be easier to debug if I could even boot into kernel 4.2.6. Anyway, I'll do some more testing and comparing with some earlier kernels and see what I can dig up.

**Comment by ehegnes** [comment]
Over the past couple of days, this issue of my touchpad not working has been less and less of an issue, even without the boot order that I specified. I cannot link any of my userspace interactions to the exacerbation of this issue, and I have no reasonable theories regarding the possible reason behind this silliness.

As such, I am closing this issue. Thanks, @raphael, for your time concerning this matter!
