### ISSUE TITLE
archlinux makepkg fails include/linux/module.h:73:1

### ISSUE THREAD

**Issue by aa0na** [raphael/linux-samus#59]
In file included from include/linux/iio/trigger.h:10:0,
                 from drivers/iio/gyro/itg3200_buffer.c:20:
include/linux/module.h:73:1: internal compiler error: Segmentation fault
 extern void cleanup_module(void);
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://bugs.archlinux.org/> for instructions.
scripts/Makefile.build:258: recipe for target 'drivers/iio/gyro/itg3200_buffer.o' failed
make[3]: *** [drivers/iio/gyro/itg3200_buffer.o] Error 1
scripts/Makefile.build:403: recipe for target 'drivers/iio/gyro' failed
make[2]: *** [drivers/iio/gyro] Error 2
scripts/Makefile.build:403: recipe for target 'drivers/iio' failed
make[1]: *** [drivers/iio] Error 2
Makefile:949: recipe for target 'drivers' failed
make: *** [drivers] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

thanks, chuck

**Comment by raphael** [comment]
This looks like an issue with the compiler. Are you able to compile a vanilla kernel tree? for reference this is what I have:
```
$ gcc --version
gcc (GCC) 5.2.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by aa0na** [comment]
There was an option to compile the headers and I said no.  That was my error.  I thought I closed this after commenting.  Thanks for nthe reply.
