### ISSUE TITLE
Cannot install docker because of absence of aufs

### ISSUE THREAD

**Issue by pekim** [raphael/linux-samus#60]
Do the `.deb`s not install aufs? Or have I screwed up somewhere along the line?

```
mike@chrx:~$ uname -a
Linux chrx 4.2.6ph+ #1 SMP Tue Nov 10 13:23:37 PST 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Output of docker check-config script.
```
...
- Storage Drivers:
  - "aufs":
    - CONFIG_AUFS_FS: missing
  - "btrfs":
    - CONFIG_BTRFS_FS: enabled (as module)
  - "devicemapper":
    - CONFIG_BLK_DEV_DM: enabled (as module)
    - CONFIG_DM_THIN_PROVISIONING: enabled (as module)
  - "overlay":
    - CONFIG_OVERLAY_FS: enabled (as module)
  - "zfs":
    - /dev/zfs: missing
    - zfs command: missing
    - zpool command: missing
```

```
mike@chrx:~$ cat /proc/filesystems 
nodev	sysfs
nodev	rootfs
nodev	ramfs
nodev	bdev
nodev	proc
nodev	cpuset
nodev	cgroup
nodev	tmpfs
nodev	devtmpfs
nodev	binfmt_misc
nodev	configfs
nodev	debugfs
nodev	securityfs
nodev	sockfs
nodev	pipefs
nodev	devpts
nodev	hugetlbfs
nodev	autofs
nodev	pstore
nodev	mqueue
	ext2
	ext4
	fuseblk
nodev	fuse
nodev	fusectl
```

**Comment by raphael** [comment]
My understanding is that aufs4 requires a custom tree to be enabled (at least according to http://aufs.sourceforge.net/). That being said why are you not using devicemapper? this tends to be the most commonly used backend nowadays (this is what I use on my box running this kernel).

**Comment by pekim** [comment]
The installation of docker failed (following instructions from https://docs.docker.com/engine/installation/ubuntulinux/), and it appeared that the problem was because of absence of aufs. I will take another look and check whether I misinterpreted the failure.

**Comment by pekim** [comment]
This is what led me to the conclusion that the absence of aufs was the problem.

```
mike@chrx:~$ sudo apt-get install docker-engine 
...
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
dpkg: error processing package docker-engine (--configure):
```

```
mike@chrx:~$ systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2015-11-24 19:59:18 GMT; 31s ago
     Docs: https://docs.docker.com
  Process: 8499 ExecStart=/usr/bin/docker daemon -H fd:// (code=exited, status=1/FAILURE)
 Main PID: 8499 (code=exited, status=1/FAILURE)

Nov 24 19:59:18 chrx systemd[1]: Starting Docker Application Container Engine...
Nov 24 19:59:18 chrx docker[8499]: time="2015-11-24T19:59:18.450166138Z" level=info msg="API listen on /var/run/docker.sock"
Nov 24 19:59:18 chrx docker[8499]: time="2015-11-24T19:59:18.451674495Z" level=error msg="[graphdriver] prior storage driver \"aufs\" failed: driver not supported"
Nov 24 19:59:18 chrx docker[8499]: time="2015-11-24T19:59:18.451705179Z" level=fatal msg="Error starting daemon: error initializing graphdriver: driver not supported"
Nov 24 19:59:18 chrx systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Nov 24 19:59:18 chrx systemd[1]: Failed to start Docker Application Container Engine.
Nov 24 19:59:18 chrx systemd[1]: docker.service: Unit entered failed state.
Nov 24 19:59:18 chrx systemd[1]: docker.service: Failed with result 'exit-code'.
```

**Comment by raphael** [comment]
Hmm looks like I was wrong in thinking that `devicemapper` had become the default: https://github.com/docker/docker/blob/729c9a97822ebee2c978a322d37060454af6bc66/daemon/graphdriver/driver_linux.go#L47-L54. `aufs` is apparently the preferred option, however it is not supported by the upstream Linux kernel.

That being said I am using devicemapper on my box just fine so the question is why docker isn't falling back on it on your box. I'm guessing it may have to do with missing libraries to support the devicemapper storage backend. TL;DR do you have the `device-mapper` package installed?

**Comment by pekim** [comment]
Yes, I've managed to start the daemon in the foreground forcing it to use devicemapper for storage. I don't know why it couldn't fall back to it.

It doesn't look like it's related to this repo at all. Sorry to have troubled you.

**Comment by ukuko** [comment]
see here, it worked for me: https://github.com/moby/moby/issues/14026#issuecomment-128055691
