### ISSUE TITLE
Error in i915 drm: CPU pip A FIFO underrun

### ISSUE THREAD

**Issue by bendavis78** [raphael/linux-samus#62]
I've been having issues with my screen blanking every now and then when I switch between my browser window and terminal. The screen blanks for a couple seconds and then comes back on. This only *seems* to happen when I use an external monitor. I finally decided to look at my kernel log and it showed this error (same timestamp as when the blanking occurred):

    [drm:intel_cpu_fifo_underrun_irq_handler [i915]] *ERROR* CPU pipe A FIFO underrun

My kernel version/release is `4.2.4-8ph #1 SMP Fri Nov 6 20:11:55 CST 2015`

**Comment by raphael** [comment]
This is a known issue with the i915 driver (see https://bbs.archlinux.org/viewtopic.php?id=196370) for example. Unfortunately there is no fix yet from upstream. Closing since as this bug isn't related to the modifications done in this tree.
