### ISSUE TITLE
mainline?

### ISSUE THREAD

**Issue by rolandoam** [raphael/linux-samus#63]
Do you know if anyone has made any patches to get these changes into mainstream linux?

**Comment by colemickens** [comment]
I'm curious about this as well. It seems last time I tried a mainline kernel, everything but sound worked. Are the patches remaining fairly minimal? I'm looking to maybe provide this package for NixOS but I'm not sure what all is still needed.

**Comment by funkaster** [comment]
For me with a stock Ubuntu "generic" kernel, everything works except:

* sound
* keyboard backlight

The rest seems to be pretty smooth.

**Comment by aeroevan** [comment]
I've started poking at sound but don't really know what I'm doing. I have something that builds, so that's something I guess: https://github.com/aeroevan/linux

I'm honestly surprised those drivers haven't made it upstream yet (I just got my pixel for christmas, so am just figuring out the quirks).

**Comment by bgemmill** [comment]
Let's see what happens if we make a request:
https://code.google.com/p/chromium/issues/detail?id=573776&thanks=573776&ts=1451786149

**Comment by aeroevan** [comment]
Keyboard backlight was easy enough: https://github.com/aeroevan/linux/tree/for-leds.

I've emailed the chromium developers and got a response which is more than I was hoping for, so here's hoping drivers are submitted for 4.5.

**Comment by raphael** [comment]
yeah that would be nice indeed. I tried contacting the driver maintainers before I started this repo to no avail.

**Comment by raphael** [comment]
I just updated this repo to `4.3.3`. The latest release and `linux-samus4` AUR package will install that version. I did notice the touchpad having some issues "sometimes". If I run `xinput` the Id of the touchpad has to be 9 otherwise it won't work. Rebooting seems to fix it.

**Comment by aeroevan** [comment]
leds driver is submitted for review: http://permalink.gmane.org/gmane.linux.leds/4276

**Comment by bgemmill** [comment]
@aeroevan That's awesome. Is there anything I can help with on the sound side?

**Comment by colemickens** [comment]
Same question on the sound side - it'd be cool if it were submitted for the 4.5 merge window. Thanks for the efforts!

**Comment by funkaster** [comment]
@aeroevan did you get feedback on the leds driver?

**Comment by aeroevan** [comment]
@funkaster the latest patch is here: https://lkml.org/lkml/2016/3/8/709

Still making progress, but not merged in yet.

**Comment by raphael** [comment]
awesome!

**Comment by christianbundy** [comment]
I apologize in advance if this is a silly question (and *please* don't take this as a criticism), but is there a general timeline for these sorts of things? I've never paid attention to an effort to get code merged into Linux, so I'm not sure whether the "normal" timeline is 3 days, 3 weeks, 3 months, 3 years, etc.

Is there a "normal" timeline for changes like these, or some ballpark idea of when it might get merged? Thanks!

**Comment by sprc** [comment]
Looks like sound was submitted upstream yesterday:

https://lkml.org/lkml/2016/8/14/207

**Comment by sprc** [comment]
Lightbar patch was successfully upstreamed back in March.

https://lkml.org/lkml/2016/5/11/779

**Comment by raphael** [comment]
Thanks for the pointer! I applied the patches to 4.7 and sound is working just fine. I'm also not having any sleep issues like I did on 4.5.  I released v4.7-1 that uses the 4.7 kernel patched with these upstream patches.

**Comment by colemickens** [comment]
So the sound was actually upstreamed? https://lkml.org/lkml/2017/9/13/300

Do we need this repo then if we don't want the extra ChromeOS specific patches? What would I miss if I moved to mainline? (I didn't think sound ever worked for me there, but maybe there's still some init script needed on mainline)?

**Comment by colemickens** [comment]
well, I booted mainline and it works now. I think I did have to run your setup scripts though. Before doing so, when I was just on the latest mainline in Arch, I wasn't seeing the Stereo devices in `pavucontrol`...

**Comment by raphael** [comment]
Yup mainline works fine now. The only thing this kernel does is have more specific configs which must provide a 0.1% performance increase :-) (okay maybe a bit more - not going to run benchmarks - but I have noticed anecdotally that the "Processor family" option which is set to "Generic-x86-64" in the vanilla kernel and "Core 2/newer Xeon" in this one seems to affect performance in a noticeable way).
