### ISSUE TITLE
resume from suspend needs three fingle salute

### ISSUE THREAD

**Issue by colemickens** [raphael/linux-samus#65]
This has plagued me since I got the device and put tsowell's linux-samus on it. I've recently reinstalled Arch so that it dual boots with ChromeOS and have been booting ChromeOS from time to time to get firmware updates.

Despite this, I still often retrieve my laptop from my bag, or from sitting on my desk closed, and find that it is totally unresponsive. When I open it, the lid lightbar lights up with the usual Chrome colors and just stays like that. The keyboard is not lit, the backlight is not lit.

It does not respond to the power button being pressed. I have to hold tap Esc+Refresh+Power. It immediately boots into recovery mode and tells me I don't have install media. Then I power it off and then can power it back on normally.

I'm curious if this happens to others?

**Comment by ethanmad** [comment]
I've had this happen a couple of times, but it's not often. Typically I can
solve it by closing and opening the lid a few times or holding down the
power button to shut down.

On another note: is having ChromeOS installed important? Is there no other
way to get firmware updates? Are those updates important?

**Comment by qivittoq** [comment]
I see the same issue. It worked fine for some versions, then somewhere down the line it became  mostly unresponsive, for me.

**Comment by raphael** [comment]
FWIW can't say that I've seen this happened (never had to use the Esc+Refresh+Power combination).

**Comment by colemickens** [comment]
Kinda grasping in the dark here... Do you use laptop-mode-tools? I'm just wondering what I'm doing differently. Using gnome3+gdm.

**Comment by raphael** [comment]
I use KDE (plasma 5) and sddm. I don't have laptop-mode-tools installed. Here are the entries in `/var/log/messages

```

**Comment by colemickens** [comment]
I haven't had this issue happen at all when using wayland/orbment on NixOS. I don't have any concrete proof, but I always had suspected it was related to `gdm`. We don't need to keep this open on my account anymore. If it happens again and I get some useful data I can revisit.

**Comment by raphael** [comment]
great, thanks for the update. Will have to checkout wayland...
