### ISSUE TITLE
Touchpad.sh doesn't run

### ISSUE THREAD

**Issue by burntcookie90** [raphael/linux-samus#66]
getting the following error

```
raptor3 :: linux-samus/scripts/setup *master* ./touchpad.sh     
+ echo Compiling libgestures
Compiling libgestures
+ git clone https://github.com/hugegreenbug/libgestures
Cloning into 'libgestures'...
remote: Counting objects: 1449, done.
remote: Total 1449 (delta 0), reused 0 (delta 0), pack-reused 1449
Receiving objects: 100% (1449/1449), 2.04 MiB | 2.27 MiB/s, done.
Resolving deltas: 100% (350/350), done.
Checking connectivity... done.
+ cd libgestures
+ ./apply_patch.sh
./touchpad.sh: line 6: ./apply_patch.sh: No such file or directory
```

seems like the dependent library is missing an expected file

**Comment by raphael** [comment]
Hmm yeah this script was work in progress, it doesn't seem to be necessary and I should probably remove it entirely (the touchpad seems to work well enough with the default driver). Is there a reason you were using it? or just poking around?

**Comment by burntcookie90** [comment]
Yeah I was just poking around, wanted to see if it supported gestures but then realized that might be Xorg limitation

**Comment by raphael** [comment]
I fixed the script and I'm using the Atmel driver now. Not seeing a huge difference tbh.

**Comment by colemickens** [comment]
(libinput works really well, even under X. I prefer it to synaptics and atmel)

**Comment by burntcookie90** [comment]
@colemickens X doesn't support touchpad gestures though right?

**Comment by colemickens** [comment]
I'm not really sure about that. I would presume not, just imagining what xorg is expecting from it's input drivers. I'm pretty sure that GNOME is adding Gestures either in 3.18 or 3.20 but I know that they're Wayland specific.
