### ISSUE TITLE
Charging Forever

### ISSUE THREAD

**Issue by burntcookie90** [raphael/linux-samus#67]
Probably not an issues with `linux-samus` directly but I'm wondering if you guys are seeing a similar issue, and whether it could be kernel level.

```
raptor3 :: ~ » acpi   
Battery 0: Charging, 100%, charging at zero rate - will never fully charge.

```

Could we have a way to stop charging at 100% (or maybe even at a configurable percentage).

**Comment by funkaster** [comment]
I'm seeing the same thing. This is happening even (AFAIK) with the stock kernel:

```
uname -a && acpi
Linux nnn 4.2.8ph+ #1 SMP Thu Dec 24 07:25:15 PST 2015 x86_64 x86_64 x86_64 GNU/Linux
Battery 0: Charging, 100%, charging at zero rate - will never fully charge.
```

**Comment by raphael** [comment]
yup same here.
