### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by roobyz** [raphael/linux-samus#70]
After updating to 4.3 samus kernel, the screen goes black after booting. I am able to "blind" log into one of the consoles and type reboot successfully so it definitely didn't crash. Even the failsafe fails to have a screen. The regular 4.3 kernel works fine but with no sound.

**Comment by ehegnes** [comment]
I'll bet the issue stems from improper framebuffer support in the config file. I'm not quite satisfied with the config myself. I'll be submitting a pull request with fixes shortly.

**Comment by raphael** [comment]
Strange, the config hasn't changed much between 4.2 and 4.3 (maybe that's the issue...). Looking forward to your PR @ehegnes.

**Comment by ehegnes** [comment]
@roobyz are you booting into a framebuffer or a graphical login manager? If you're not booting into a framebuffer, my idea isn't going to solve your issue.

**Comment by roobyz** [comment]
I'm running Arch Linux and boot into LightDM and then log into Gnome 3.18.

**Comment by ehegnes** [comment]
Hmm. I thought maybe it was due to KMS loading late, but that shouldn't affect an X.Org server...

**Comment by roobyz** [comment]
I believe it is related to encryption. I removed quiet, splash and plymouth from my boot settings and I don't even get the prompt for the passphrase with the Samus kernel. Oddly enough, it only seems to ask for the passphrase when splash is enabled... and immediately after entering it, the backlight for the keyboard goes off. My guess is the backlight for the screen also goes off as well... which is why my screen is black.

**Comment by ehegnes** [comment]
Are all of your volumes encrypted, including boot? I don't know much about volume encryption, but I'll do my best to help. Since the kernel code relating to encryption is the same across vanilla and samus kernels (right?), maybe the issue is in configuration.

Can you post the config file from your working vanilla kernel in a separate link? Boot in and run `zcat /proc/config.gz > file` to write the running kernel's config to a file.

It maybe coincidental, or even a product of my own changes, but [I receive symbol errors from `depmod` when trying to install kernel modules](https://gist.github.com/ehegnes/e68adca6040934c38792). The errors seem to relate to encryption modules, but I don't know if the kernel that ships with this repo had the same errors.

**Comment by roobyz** [comment]
No, I have a boot partition and everything else is encrypted. Pretty standard stuff.  Attached is the vanilla Arch kernel config file. I ran a unified diff and there are a lot more differences than I expected. I hope this helps.

[config.arch-vanilla.zip](https://github.com/raphael/linux-samus/files/81872/config.arch-vanilla.zip)

**Comment by wulvyrn** [comment]
I'm not running encryption and the last thing I see is the initramfs and then nothing.
I have used i3 in the past starting x after console login but that's no longer possible.

My workaround is gdm and gnome shell.  Time to look for a mouse, trackpad is another issue by itself.

**Comment by roobyz** [comment]
Hi Wulvyrn... are you saying that if you use GDM/Gnome then it works, otherwise you get a blank screen as well? I'm running LightDM and Gnome. I'm wondering if switching to GDM resolves the blank screen issue.

**Comment by wulvyrn** [comment]
The black screen is still there.  Running gdm just starts x.  I have a trackpad in gdm but then gnome shell launches in vt2, the trackpad is no longer.

**Comment by colemickens** [comment]
@wulvyrn that's because gdm is using wayland (and thus libinput). You don't have an input driver installed for X. Install `xorg-input-synaptics` or `xorg-input-cmt` or `xorg-input-libinput`.

**Comment by wulvyrn** [comment]
I have xorg-input-cmt-git under arch Linux.

**Comment by roobyz** [comment]
I kept a copy of the 4.2 kernel and tried installing the 4.3 kernel. Both kernels failed to boot, I believe because something in the Arch install script caused the initramfs to be built incorrectly. There were a bunch of error messages during boot but it was too fast to read. I reinstalled the 4.2 from the 4.2-11 version of the script and then 4.2 booted, but the 4.3 kernel failed to load the encrypt password screen.

**Comment by roobyz** [comment]
WOW... I figured it out... it looks like the install script and compiled kernel from the git repo are not currently working. Instead, I used "yaourt -S linux-samus4" to compile/install from AUR and everything worked as expected.

**Comment by raphael** [comment]
Interesting... I wonder what's different (fwiw the packages in the repo work fine for me).

**Comment by wulvyrn** [comment]
@roobyz are you running the linux-samus4 kernel?  I installed from yaourt and it didn't boot to the new kernel.  

When I ran grub-mkconfig -o /boot/grub/grub.cfg, it boot to the new kernel but the last thing I see is the initramfs loading and then nothing.  The OS is running but nothing on the console.

**Comment by wulvyrn** [comment]
the new release 4.4 does not have this issue.

uname -r 
says i'm running 4.3.3-1ph

i downloaded the PKGBUILD from aur and built it with makepkg -s

**Comment by raphael** [comment]
I was trying to fix the weird issues with the split package but that didn't end well. I'll revert to the previous scheme.

**Comment by wulvyrn** [comment]
This seems to be working now as I can console login with out an issue.  Could this be closed?

**Comment by raphael** [comment]
Yup, thanks. Swapping this against audio not working in 4.4...

**Comment by roobyz** [comment]
Thanks raphael... definitely fixed! Much appreciated. Out of curiosity, what caused the issue?

**Comment by zedinosaur** [comment]
I'm not sure if I should reopen this bug or open a new one but I'm seeing something very similar to this on my Debian system.
