### ISSUE TITLE
Fails to install from the AUR

### ISSUE THREAD

**Issue by slang800** [raphael/linux-samus#71]
After [quite a bit of compiling](http://pastebin.com/LBJDttc2), it fails to install with "duplicate target":

```
$ packer -S linux-samus4

[...]

==> Tidying install...
  -> Purging unwanted files...
  -> Removing libtool files...
  -> Removing static library files...
  -> Compressing man and info pages...
==> Creating package "linux-samus4"...
  -> Generating .PKGINFO file...
  -> Adding install file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Starting package_linux-samus4-headers()...
==> Tidying install...
  -> Purging unwanted files...
  -> Removing libtool files...
  -> Removing static library files...
  -> Compressing man and info pages...
==> Creating package "linux-samus4-headers"...
  -> Generating .PKGINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Starting package_linux-samus4-docs()...
==> Tidying install...
  -> Purging unwanted files...
  -> Removing libtool files...
  -> Removing static library files...
  -> Compressing man and info pages...
==> Creating package "linux-samus4-docs"...
  -> Generating .PKGINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: linux-samus4 4.3-2 (Wed Jan  6 06:46:10 EST 2016)
loading packages...
error: 'linux-samus4-headers-4.3-2-x86_64.pkg.tar.xz': duplicate target
error: 'linux-samus4-docs-4.3-2-x86_64.pkg.tar.xz': duplicate target
```

**Comment by raphael** [comment]
It works fine with `yaourt` but it could just be that it's more lenient. You could use that in the mean time - I'll take a look at packer.

**Comment by ethanmad** [comment]
Is this a new issue with the latest release? I haven't updated yet, but have never had problems with `pacaur`.

**Comment by raphael** [comment]
I doubt it - it's the exact same PKGBUILD

**Comment by slang800** [comment]
Yeah, I tried a few days ago on an earlier release & hit the same issue... I just didn't have time to file an issue then. I'll give `yaourt` a shot & report back.

**Comment by raphael** [comment]
Following up on this: have you tried `yogurt` ? Does `packer` work with the AUR kernel package?

**Comment by wulvyrn** [comment]
today i tried the following:

1.  git clone linux-samus
```
cd aur
makepkg -s
```
builds without error

2.  yaourt -S linux-samus4
builds without error

3.  downloaded linux-samus4.tar.gz from aur
```
tar xvf linux-samus4.tar.gz
cd linux-samus4
makepkg -s
```
1st time it failed to complie.  2nd time it did build without error.
as to why, well that's beyond my brain level at this time

**Comment by slang800** [comment]
@raphael: I tried installing with yaourt, and that worked perfectly.

**Comment by raphael** [comment]
OK I'll close this for now, thanks for verifying.
