### ISSUE TITLE
Kernel config fixes

### ISSUE THREAD

**Issue by ehegnes** [raphael/linux-samus#72]
I'd like to improve the default kernel config. Specifically, I'd like to configure the following:

- More comprehensive file system support built-in to the kernel (for those of us booting with root partition types different than the standard; I use F2FS, for example)
- ACHI support built-in (I have personally experienced issues with the root volume not mounting due to this -- results in a kernel panic as a module)
- Framebuffer support built-in (so we can see the kernel log on boot for those of us who don't use a graphical login; would probably fix #70)

Further, the fact that the kernel's `.config` file is a symlink results in git getting confused after configuring with `make menuconfig` or other such utilities. I'd like to use a real `.config` file at `build/linux/.config` and hard-link or soft-link to `scripts/config`.

Do I have best wishes proceeding with these changes?

**Comment by ehegnes** [comment]
These changes aren't necessarily "fixes" unless people are experiencing issues. I am personally experiencing issues caused by the config, but my necessities may be a mite different on Gentoo than they would be on Arch or Debian.

I'm actually surprised anybody can boot with the current config, considering that not a singe file system is built-in.

If these changes are unwanted, I'll simply fork and be on my merry way!

**Comment by raphael** [comment]
These changes sound great! I am a but confused about some of your assertions. For example pretty much all file systems are supported: https://github.com/raphael/linux-samus/blob/master/scripts/config#L4506-L4583. But please make the changes you need to make it work for you, this kernel should support all environments.

**Comment by ehegnes** [comment]
Ah, maybe it has to do with my lack of an initramfs. I need my boot partition's file system to be built-in. Alas, if these issues are not persistent across other more common distros, I might as well not "fix" what isn't broken.

**Comment by raphael** [comment]
Well others have reported issues booting, see #54 for example so I was hoping you were onto something that could help with that.

**Comment by ehegnes** [comment]
Oh, I actually do have a fix for that!

**Comment by ehegnes** [comment]
Closing this because this isn't a very specific issue, and the changes that I brought up should be implemented in their own issue tickets, anyway -- if ever.

**Comment by colemickens** [comment]
@ehegnes FWIW, you're apparently not alone: https://github.com/NixOS/nixpkgs/pull/12309#issuecomment-171545454

**Comment by raphael** [comment]
I actually took some of the suggestions in with the latest build (https://github.com/raphael/linux-samus/commit/5456fa47b90026bc6f3c41de51a6048607f4e485#diff-fbc1eef3364b71e1e9debe976c54d7eaR569). I'm happy to add more -  I just took the ones I knew were safe and I understood. Just tell me why some option is needed and I'm happy to add.

**Comment by ehegnes** [comment]
Oh, great! I was just maintaining my own fork with my personal config, but it seems like others could benefit from some changes. Thanks, @colemickens, for your example.

It's a safe bet to compile all filesystem drivers into the kernel so that people can boot on whatever filesystem they like without resorting to an `initrd` or `initramfs`. I'll PR that change shortly.
