### ISSUE TITLE
Sound not working with 4.4

### ISSUE THREAD

**Issue by raphael** [raphael/linux-samus#80]
From `dmesg`:
```
[    4.416443] haswell-pcm-audio haswell-pcm-audio: error: DMA request channel failed
[    4.416473] haswell-pcm-audio haswell-pcm-audio: error: failed to load firmware
```

**Comment by roobyz** [comment]
same issue here.

**Comment by steviedons** [comment]
Yep, just upgraded to the 4.4 kernel and got exactly the same error in dmesg.

**Comment by raphael** [comment]
I think it has to do with:```
sst-acpi INT3438:00: DesignWare DMA Controller, 0 channels``` This should say *8* channels and not 0.

**Comment by raphael** [comment]
Fixed the sound in release 4.4-3.

**Comment by steviedons** [comment]
Just updated to 4.4-3 and sound is fine, thank you for the quick updates.

**Comment by roobyz** [comment]
it's better than fine... this totally fixed the issue I had where the volume always seemed to be a bit low all the time. Many thanks for the excellent work.

**Comment by christianbundy** [comment]
@raphael how can I buy you a beer?

**Comment by raphael** [comment]
Since you ask: it'd be cool to have a PPA for this kernel. I am not using Debian or Ubuntu so it's hard for me to provide one (I tried). If there was one I'd be able to remove the binaries from this repo which would make it a lot easier to maintain...
