### ISSUE TITLE
Kernel source not updated to 4.4-x

### ISSUE THREAD

**Issue by ehegnes** [raphael/linux-samus#81]
The compiled versions were updated, but the source was not. If you run `make kernelversion` in `build/linux`, you can see that the source version is still `4.3.3`.

**Comment by raphael** [comment]
Looks correct to me: https://github.com/raphael/linux-samus/blob/master/build/linux/Makefile#L1-L3

**Comment by ehegnes** [comment]
Ah, sorry. I suppose my issue concerns only the `v4.4-1` tag: https://github.com/raphael/linux-samus/blob/v4.4-1/build/linux/Makefile#L1-L3

**Comment by raphael** [comment]
Ah yes the 4.4-1 release was buggy, that's why I did 4.4-2.

**Comment by ehegnes** [comment]
Sounds good to me. Thanks for dispelling my concern!
