### ISSUE TITLE
Possible missing firmware /lib/firmware/i915/skl_guc_ver4.bin for module i915

### ISSUE THREAD

**Issue by recri** [raphael/linux-samus#82]
This warning popped up when installing the 4.4-3 release.  The whole message was:

update-initramfs: Generating /boot/initrd.img-4.4.0ph+
W: Possible missing firmware /lib/firmware/i915/skl_guc_ver4.bin for module i915

The firmware is in Debian firmware-misc-nonfree (20160110-1) identified as:

* Intel "Skylake" GuC firmware, version 4.3 (i915/skl_guc_ver4_3.bin,
   i915/skl_guc_ver4.bin)

**Comment by ehegnes** [comment]
Our Pixels use Intel's "Broadwell" line, no? Without any kind of research to back up my claim, I'm going to assume that you're safe without that Skylake firmware. :)

Somebody please correct me if I'm mistaken!

**Comment by recri** [comment]
Sounds like a reasonable explanation.  I've got way too many years of Intel product code names in my head to recognize new ones.
