### ISSUE TITLE
LVM2 hook in mkinitcpio not working

### ISSUE THREAD

**Issue by evanlong19** [raphael/linux-samus#84]
I am trying to run an Arch Linux encrypted drive setup using LUKS with LVM on top for a partitioning scheme.  

https://wiki.archlinux.org/index.php/Dm-crypt/Encrypting_an_entire_system#LVM_on_LUKS 

However, I am running into problems when recreating the ramdisk.  As per the instructions above, I added the "lvm2" and "encrypt" build hooks to my /etc/mkinitcpio.conf file and ran "mkinitcpio -p linux-samus4."  The lvm2 build hook is throwing module not found errors for the "dm-cache" and "dm-cache-mq" modules.  

This does not happen when I build the ramdisk for the standard kernel, just for linux-samus4, which makes me think that this is relevant here.

**Comment by raphael** [comment]
Could you try enabling `Device Drivers -> Multiple devices driver support (RAID and LVM) -> Device mapper support / Cache target (EXPERIMENTAL)` (run `make nconfig` in `build/linux-patched`) then building and installing the resulting kernel? If that works I'll enable the option in the next release.

**Comment by evanlong19** [comment]
Yep that worked like a charm.  Thanks!

**Comment by raphael** [comment]
OK thanks for confirming, next build will have support built-in.
