### ISSUE TITLE
touchpad script enable-atmel.sh - touchpad device not found - exiting - intermittent

### ISSUE THREAD

**Issue by wulvyrn** [raphael/linux-samus#85]
Sometimes the touchpad works and sometimes not.
The following is data when it isn't working:
```
dmesg | grep Touchpad
[    7.789511] input: Atmel maXTouch Touchpad as /devices/pci0000:00/INT3432:00/i2c-0/i2c-ATML0000:01/input/input12
sudo /usr/local/bin/enable-atmel.sh 
touchpad device not found - exiting
```
i put the executable and script in /usr/local/bin as it seemed more fitting to where user only stuff would go vice a system package.
any ideas how to fix or address this?  i'm willing to hack at it to get it working.  thanks...

**Comment by wulvyrn** [comment]
./mxt-app in script should read
mxt-app since it should be in a directory in the PATH

it is not working in .xinitrc.  looking into that now.

**Comment by opticron** [comment]
I'm having this same problem on the 4.4 kernel. The touch pad rarely works while the touch screen can be gotten working after a couple attempts with enable-atmel.sh.

**Comment by opticron** [comment]
I also just discovered that while a reboot will not affect functionality, a full shutdown and then boot back up will get it back to a working state.

**Comment by ehegnes** [comment]
Hrmm. I came up with that messy workaround, and I can't say I'm too surprised it's already failed. I'm still on 4.3, but I'll install 4.4 shortly to test this myself.

**Comment by wulvyrn** [comment]
i think i have it fixed in my fork.  so far it's worked though several reboots.

**Comment by wulvyrn** [comment]
Merged, closing this issue.

**Comment by karlfloersch** [comment]
I just upgraded from 4.1 that I installed a long time ago, to the most recent version on yaourt (updated 2016-02-24 23:45). I seem to be running into this issue.

My touchscreen works, but my touchpad is completely unresponsive. I've rebooted many times and shutdown once. 

This is what I run `dmsg` and `enable-atmel.sh`

```
[    1.876223] input: Atmel maXTouch Touchpad as /devices/pci0000:00/INT3432:00/i2c-0/i2c-ATML0000:01/input/input5
[karl@karlbook ~]$ sudo .bin/enable-atmel.sh
touchpad device not found - exiting
```

How can I fix this?

**Comment by karlfloersch** [comment]
Looks like it probably had to do with an incomplete update from 4.1 to 4.4. I'm going to reinstall and hopefully that will solve all the issues.
