### ISSUE TITLE
Fedora compatibility 

### ISSUE THREAD

**Issue by xdaxdb** [raphael/linux-samus#89]
If I try to compile this for Fedora what are the odds that it will work? I'm not all that familiar with compiling the kernel, or anything for that matter.

I notice that most of the efforts to put Linux on the Pixel 2015 like this one or Crouton are Ubuntu, Debian, or Arch related. Crouton I get, but in this case I'm not sure. Is there something about this hardware that is going to make running Fedora more difficult than Debian?

I work with Red Hat and CentOS, so I prefer to use Fedora on my laptops.

**Comment by ehegnes** [comment]
I'm not familiar with Fedora, but after some searching online, it looks like you *can* install this kernel using the method described in the README. (I don't believe Fedora needs a custom patchset to be applied like some distros). However, I think the Fedora folk prefer building an RPM out of the kernel. You can do this by installing `rpmdevtools` and running `make rpm` from the root of the kernel tree, `build/linux` (there may be a few more steps involved than just that).

I'd be glad to download a Live CD and test a procedure for building an RPM of this kernel! Alternatively, you may be able to use the command `alien` to convent the `.deb` file that is located in `build/debian` to a `.rpm` file, but I can't attest to the reliability of this procedure.

**Comment by gaika** [comment]
Works fine on Fedora 23.

**Comment by ehegnes** [comment]
Plus, Fedora has used `systemd` as the default init system since release 15, in 2011, so all of the `systemd` scripts are also compatible.

**Comment by ehegnes** [comment]
I think this can be closed, unless @xdaxdb would like a writeup on the RPM method of install.

**Comment by old486whizz** [comment]
I had to alter the build config a fair bit for kernel 4.2 or 4.3, because fedora uses selinux, etc .
I do have a copy of the build config file I've used - although it leaves a footprint of about 2G of modules (whereas if you're familiar with Fedora kernels they come with maybe 800M of modules)..

**Comment by tom-schultz** [comment]
I'm having some trouble with this. I got the kernel built by running nconfig (changing nothing), then ran make rpm, then installed the RPM with "rpm -ivh $HOME/rpmbuild/RPMS/<arch>/kernel-<version>.<arch>.rpm". When I rebooted the touchpad and touchscreen didn't work, and sound didn't either. The sound script seemed to be find but sound wasn't available. Any thoughts?

**Comment by raphael** [comment]
Have you tried installing the rpm files included in the release?

[https://github.com/raphael/linux-samus/archive/v4.4-6.zip](https://github.com/raphael/linux-samus/archive/v4.4-6.zip)

**Comment by tom-schultz** [comment]
Nope... I didn't realize it came with RPM files. I'll try that :D

**Comment by tom-schultz** [comment]
Where are those RPM files? I did a find in the folder and came up with nothing.

**Comment by raphael** [comment]
There are in [build/debian](https://github.com/raphael/linux-samus/tree/v4.4/build/debian)

**Comment by tom-schultz** [comment]
No worries! The process for building a Fedora kernel I found on the wiki seems to be full of Fedora specific tools so I had a hard time separating out what I needed to run from their specific process.

@old486whizz, any chance I could get that config from you?
