### ISSUE TITLE
problems logging in, loosing touchpad

### ISSUE THREAD

**Issue by stefanwiegmann** [raphael/linux-samus#94]
hi, thanks for all your work!

I am on arch and plasma. since a few kernel versions (sorry, not able to pinpoint) it sometimes takes me several tries to log into plasma through sddm. Almost every reboot now, I have no touchpad working.

Switching to mainline works (besides sound) and switching to 3.19-2 (your last of the 3-series?) works as well.

anybody else the same? not even remotely and idea what's going on. 

Edit: looked through some of the closed issues, but for me it still happens with everything uptodate.

**Comment by ehegnes** [comment]
Can you kindly elaborate on "it takes [you] several tries to log in..."? That sounds like a userspace issue...

**Comment by stefanwiegmann** [comment]
sorry, I think it is userspace. just figured it exists booting into any kernel. So, only the touchpad seems to be kernel related.

**Comment by ehegnes** [comment]
Have you tried any other DMs/WMs? [dwm](http://dwm.suckless.org/) is lightweight. [twm](https://wiki.archlinux.org/index.php/twm) is barebones, but it is commonly used to test xorg configs.

**Comment by raphael** [comment]
Please read the README for the touchpad issues.

**Comment by stefanwiegmann** [comment]
thanks, didn't see that. if I run ./enable-atmel.sh, it always fails: touchpad device not found - exiting

a modprobe didn't do anything. do i have to do anything before?

**Comment by wulvyrn** [comment]
are you using the latest enable-atmel.sh?

**Comment by opticron** [comment]
I have been having a similar issue. Description of the issue as I have experienced it:
With the recent 4.4.x kernel, a suspend or a reboot puts the atmel touch controllers into a weird state where don't communicate properly with the system. It takes a cold boot to get them working again on the 4.4 kernel.

Cold booting back into the 4.2.8 kernel resolves the issue and prevents it from happening on subsequent reboots/suspends.

**Comment by stefanwiegmann** [comment]
:-) I am getting more confused. I installed the latest linux-samus from AUR. 
That's the kernel I booted into, I clone the current repo und went to the folder and executed the script. The script gives me the error and I have no module i2c-dev loaded. Do I have to install anything else to get the module?

**Comment by wulvyrn** [comment]
the script in the readme.md needs to have mxt-app in the $PATH.  if you are using systemd, use the setup.systemd.sh script to copy the scripts and mxt-app to /usr/local/bin and it will also copy the service file to /etc/systemd/system and enable the service.  upon reboot it should  be working and also enable-atmel.sh will work as it will then be in the PATH.

**Comment by stefanwiegmann** [comment]
ha, now it worked. thanks wulvyrn! 
I ran setup.sh, enable-atmel.sh and setup.systemd.sh in that order. First reboot worked ;-) So, will close for now.

**Comment by wulvyrn** [comment]
today, upon a fresh install of i3 under arch linux - the systemd failed on the atmel.service but the script worked.  i'll do some more digging today as to why.

**Comment by stefanwiegmann** [comment]
should I open again?

**Comment by wulvyrn** [comment]
you can, as the service is failing now but the script works.

**Comment by raphael** [comment]
Not sure whether that's relevant but I've noticed in `dmesg` that the kernel does try to reset the chip on boot but somehow that either doesn't take effect or gets "overridden" later. So I'm guessing it's possible the step causes the need for the extra reset would happen after the service started. Just a random thought - could be completely off :)

**Comment by wulvyrn** [comment]
i think you are on the right track.  i'm still digging.

**Comment by wulvyrn** [comment]
I believe I found the issue.  I changed the service file on my computer to have it load after it loads the rest of the system.  under the [Service], added Type=idle.  small fix.

**Comment by raphael** [comment]
nice, thanks!

**Comment by gatorpatch** [comment]
I have the same issues, get the no touchpad found thing

**Comment by colemickens** [comment]
I have no idea if this is helpful, but I came home tonight, rebooted and could not get mxt-app to reset the device properly. I was getting a message about "[something] master [something] lied!" or something like that. I'm ashamed that I didn't write it down (I was in the tty, I guess I could have `gist`ed it.)

What I can say is... I rebooted numerous times. Each time, the same thing. Until I removed my usb3 type-c ethernet adapter. Then I rebooted and mxt-app worked as normal.

Not looking for help with it necessarily, just throwing it out as another data point. I'd not had any problems using mxt-app in other conditions. I'll pay more attention to see if this is consistent. (I've also noticed that usb3/type-c devies sometimes don't work correctly if they are plugged in during boot, so maybe something more fun is at play).

**Comment by nnutter** [comment]
FWIW, I think some of the issues here are due to 109decb which "breaks" the script as used in the `README.md`.  If you run `./setup.systemd.sh` first then `./enable-atmel.sh` will find the device because `mxt-app` was copied to `/usr/local/bin/` by `./setup.systemd.sh`.

**Comment by c0z3n** [comment]
@nnutter , yeah, that was my experience this evening. 

also, running `./setup.systemd.sh` appeared successful but didn't actually copy the files into /usr/local/bin as it claimed, I had to copy them manually. not sure why
