### ISSUE TITLE
acpid handler.sh population via setup script is broken

### ISSUE THREAD

**Issue by akauble** [raphael/linux-samus#98]
SEE FIRST COMMENT FOR BUG/SOLUTION

I've got audio working fine via speakers on a fresh arch install with linux-samus. Sound script was successfully run with acpid installed. 

However, when I plug in headphones, nothing happens. The output device doesn't change and the alternate state doesn't get loaded.

I'm able to switch the output device between speakers and headphones using the pulse mixer, but it stays on whichever I select regardless of the headphones plugged state.

**Comment by akauble** [comment]
The script to populate handler.sh is very broken and pretty much just destroys that file somehow.

Replacing its contents with the following fixed all audio switching issues I had.
case "$1" in
        jack/headphone)
                case "$3" in
                        plug)
                                alsactl restore -f /opt/samus/headphones.state
                                alsaucm -c bdw-rt5677 set _verb HiFi set _enadev Headphone
                                ;;
                        unplug)

                                alsactl restore -f /opt/samus/speakers.state
                                alsaucm -c bdw-rt5677 set _verb HiFi set _disdev Headphone
                                ;;
                        *)
                                ;;
                esac
                ;;
        *)
                ;;
esac
;;

**Comment by raphael** [comment]
Do you have the original content of your `handler.sh` script? Otherwise it's hard to tell what's wrong with the `sed` commands.

**Comment by akauble** [comment]
Unfortunately I didn't think to make a copy. It looked to be looping incorrectly as the file reached a few thousand lines of the repeated code block. I'd run it again to demonstrate but I don't have time to fix my audio again right now if something goes weird with it.

I had the same problem on three separate arch installs so it should be reproducible.

**Comment by raphael** [comment]
I've tweaked  how that's done in 7c8a00312 and in my tests that seems to work fine.
